### ISSUE TITLE
dual-licence question

### ISSUE THREAD

**Issue by jeff-h** [less/less.js#1029]
Would you consider releasing LESS under GPL v2 (or something compatible with it, such as MIT), as well as the existing Apache 2?

The three big open source CMS's — WordPress, Joomla and Drupal — are all GPL2 only and thus can't incorporate this library easily, instead requiring users to manually come to github or http://lesscss.org and download it, and install it separately, which ultimately reduces adoption.

**Comment by nueckman** [comment]
It would be nice to get even a single line of feedback. Are there any thoughts about changing the licence ?

**Comment by seven-phases-max** [comment]
@nueckman

It's all above I guess. As I see it, this is not going to happen untill someone to sit and manage all those things required to get the change permission from every `less.js` codebase contributor. I assume none of (very small) Less team do actually find this pretty much abstract "race condition" (5 posts for 3 years?) to be important enough to take this quite tedious task. But obviously if anyone else finds this important enough to put *his* time for making it, he's welcome and helped.

**Comment by SomMeri** [comment]
@nueckman I do not mind adding another open source license to less or changing it to another standard open source one. 

@seven-phases-max Is it really necessary to hunt down every single small commit author for license addition?

**Comment by seven-phases-max** [comment]
@SomMeri  I'm not an expert at all, but according to above comments, https://github.com/twbs/bootstrap/issues/2054 and similar issues found elsewhere - yes, it looks like so. 
(This is weird of course, counting that the codebase was reworked and reorganized sort of several times by now... so that, I believe, roughly speaking, 99% of the code is actually written solely by @lukeapage from scratch :), but such estimations are not what these kind of things can be based upon :(

**Comment by ionas** [comment]
LGPL 2 / LGPL3 would be good. IMHO it is an excellent choice for community driven libraries.

**Comment by ionas** [comment]
@lukeapage Well as the main project's drivers/contributer(s) it is up to you to decide what should happen. I can't see why one would not want LGPL instead of MIT for LESS because there is little to gain if you keep your own LESS hacks secret from the main LESS project (is there?). 

That being said, I have no idea how the legal implications would be. My guess is: keep the old versions on MIT and only change the license on new versions. The only thing though is legal impact. You can easily use LGPL in MIT based closed source commercial projects.

So the work that @hswong3i has done is probably required in any case. Either to do the switch OR to allow for a 2nd license.

**Comment by matthew-dean** [comment]
I would suspect that we only need to contact contributors if we're still using that code. Once Luke rewrote things for plugins, probably a lot, if not most, if not all, of those pieces were replaced.

This is an open source project with no corporate interests. Is there a real concern by changing the license? If so, you could just run a "blame" on the whole project, could you not? And see if any line from a contributor other than Luke?

**Comment by matthew-dean** [comment]
> My guess is: keep the old versions on MIT and only change the license on new versions.

Or that. Less 1.x could have had one license, and 2.x can have a different license. They're re-architected enough that they're unique projects.

**Comment by ionas** [comment]
Version numbers are cheap. Switching licenses is a good enough reason to wo with SemVer major +1 version I think. So Less 3.0 could utilize LGPL2/3 (or BSD/MIT) only.

**Comment by lukeapage** [comment]
I can have a go at setting up https://github.com/beberlei/license-manager
but first I'd like the core team to decide what we want. I need to read up on the license types.

**Comment by jonschlinkert** [comment]
Regarding license type, since this project is entirely open source, MIT is the way to go.  The others are only worth considering when the project is under the dominion of an actual organization or company that might have liability or intellectual property rights to consider. Even then, many organizations still choose MIT these days. Twitter is a good example. 

just my 2c. I would expect @cloudhead might want to weigh in on this.

**Comment by jonschlinkert** [comment]
ah, and I see that he has... sorry just noticed

**Comment by ionas** [comment]
@jonschlinkert What has twitter to do with LESS in terms of an argument? Why is MIT superior to LGPL for a library/language/compiler like LESS.

**Comment by seven-phases-max** [comment]
I'd vote for MIT (LGPL? what for? beside bloating text and forever blurred edge-cases...)

**Comment by jhli** [comment]
Maybe because GPL makes peeps contribute. MIT is always nice @ free rider, see OS X or Webkit?

**Comment by jhli** [comment]
I'd also rather see MIT only over dual licensing but LGPL is even better.

**Comment by jonschlinkert** [comment]
> What has twitter to do with LESS in terms of an argument?

What do commercial projects have to do with LESS?

> You can easily use LGPL in MIT based closed source commercial projects.

**Comment by ionas** [comment]
@jonschlinkert Nevermind, I don't think we have an argument anyway. Sorry and NVM.

Just imagine a company creating some pre-processor application and extending modifying LESS for that purpose and not giving back the changes to LESS compilers. That's sad and LGPL stops that, MIT does not. It is fine if people create proprietary management tools for LESS but the LESS compiler itself should not suffer from "free but worse VS proprietary and better" because of free-as-bike-riding-beer-drinking MIT issues.

For me it is: LGPL3/LGPL2 > MIT > MIT + LGPL2/3 > MIT + Apache

**Comment by seven-phases-max** [comment]
>Just imagine a company creating some pre-processor application and extending modifying LESS for that purpose and not giving back the changes to LESS compilers. 

Too imaginary and too hypothetical bonus against real corks (while for sure LGPL is perfectly fine for JavaScript libraries, it's also extremely confusing for an average scripting guy because of its quite-c/cpp-coupled terms and concepts: "linking", "header files", "object code" etc.).

**Comment by dantman** [comment]
Why are we diving off on this tangent (talking about the merits of LGPL)?

Debating copyleft vs. permissive now is pointless. Less.js is Apache licensed and every release up to this point will remain available under an Apache no matter what new license is picked. Apache is a permisive license. And Less.js (along with the rest of the Node.js community, which I've noticed is primarily permissively licensed) has been doing quite fine so far with the permissive license.

The only reason this bug was opened at all. Was because the Apache license gives some trouble to the GPLv2(+) based projects. Not because there was an overwhelming sentiment that Less.js should switch to a copyleft license.

The only thing worth deciding, besides how to make the switch, is whether we Apache/LGPL2+ dual-license to fix the issue or drop down to MIT to fix it.

Note that the Apache license includes patent protection which MIT doesn't. It's not exact, but you can consider Apache 2.0 to roughly equal MIT + Patent protection. So the question is basically do we ditch the patent protection (switch to MIT). Or try to keep it (dual-license with LGPL2+ to add GPL compatibility).

**Comment by seven-phases-max** [comment]
@dantman  

Indeed.

**Comment by ionas** [comment]
Why?
1. Because single licensing is easier than dual licensing maybe? (is it not?)
2. Because when choosing a single license MIT and LGPL are both good candidates? (are they not?)
3. Because not being compatible with GPL2 would have not been an issue if LGPL2/LGPL3 (or MIT) had been chosen up front?

Side note 1: http://en.swpat.org/wiki/Patent_clauses_in_software_licences#LGPL_2.1 - I did not dig into LGPL3 but GPL3 did copy Apache 2's patent clauses it seems.
Side note 2: it is not about the current source code and its license but future versions.

**Comment by matthew-dean** [comment]
> Just imagine a company creating some pre-processor application and extending modifying LESS for that purpose and not giving back the changes to LESS compilers. 

Errr I've done that. The changes I made were not applicable to Less core. We want to adapt a license to prevent that? Why? What's the benefit to Less in being restrictive about its use?

**Comment by ionas** [comment]
@matthew-dean well and the spirit of (L)GPL is to let the community of developers that created the foundation you used to work upon decide if those changes are relevant to them, too. They can then learn and re-use. Improve and innovate. The MIT model clearly failed as you can see in Darwin.

The benefit is very clear: If you are utilizing a (l)GPL'ed community effort you are obliged to share/give back. (L)GPL is basically a free-rider stop in the FOSS world*.

Well, its not up to me anyway, I'd still rather prefer one MIT license over a dual licensing model, it is just that I don't see why it should not be LGPL and the reason you stated above is actually a pro LGPL argument.

**Comment by matthew-dean** [comment]
Well as both a community manager and a user of Less, I'd prefer if people didn't submit changes that they knew to be irrelevant and ask me to decide about it, because that's more work for me. Sure, I'd love if people submit pull requests for things they feel are of a benefit, but I don't want to be one of the people that has to decide which it is, each and every time, for every change. I don't know much about licensing, but if that's what LGPL means, great then, consider me anti-LGPL. People are volunteering their time here. Adopting a license which necessitates using more of their time is not a fair exchange. I'm happy to contribute and help maintain Less because it's been tremendously useful to a lot of people. I don't really care if people use it to build a doomsday machine.

As @seven-phases-max, all of these scenarios are hypothetical. As far as we know, no one yet has built a doomsday machine. So, rather than try to make something restrictive and have people ask permission for everything, it seems more of a community benefit to license as permissively as possible, without allowing someone else to release to the public something else called "Less.js" that uses our logo and assets and does the same thing.

**Comment by jhli** [comment]
The whole sharing 'pollution' argument is void. Your changes just have to be LGPLed FOSS and distributed somehow.

**Comment by jhli** [comment]
And if you want to protect a brand that has imho little to do with the compiler's source license. See how diffivult that is to pull of @ Firefox/Debian.

**Comment by matthew-dean** [comment]
> The whole sharing 'pollution' argument is void. Your changes just have to be LGPLed FOSS and distributed somehow.

Ok, I'm still against that.

**Comment by matthew-dean** [comment]
@lukeapage @jonschlinkert @seven-phases-max You're all for dual-licensing with MIT?

**Comment by jhli** [comment]
Yes, cause you profit from free riding which LESS is probably creating a lot (for me too by just utilizing it).

MIT vs GPL is always a matter of economical interests. Tjose doing the heavy lifting in recent LESS versions should decide if they rather have obligation to share of invisible free riders.

I am done. I do really hope it gets to be One license only (MIT or LGPL).

**Comment by matthew-dean** [comment]
> Yes, cause you profit from free riding which LESS is probably creating a lot (for me too by just utilizing it).

lol. I have? I should check my bank accounts.

To be clear, this was more of an issue in Less 1.x, where there was no API to speak of, and many of Less's core functions were not exposed in the library. My change was to modify the browser version for an Adobe AIR environment, which had direct file access instead of HTTP requests. Yes, that code is available in a (free) open source project on Github, but I've no idea what license it would conform to as to how consumable it is.

What I found more a benefit was to give input on design of an API with the ability to create file managers separate than just "Node" and "browser" JS environments, which isn't really "licensable". But that to me was the item of greater value - contributing in a design discussion for something that would benefit a greater number of people, rather than just slap code that only served my needs somewhere. So, I'm not sure how different licensing would have made any difference in that scenario, except a more restrictive licensing raising more questions as to the requirements & obligations of software authors.

I think the more relevant point is in other projects (such as the top of the issue) where there is a direct conflict between licensing they've chosen and the Less license that prevents inclusion into other projects. So right now the problem reads as already one of too much obligation. Therefore, more obligation doesn't logically follow as the answer.

**Comment by ionas** [comment]
As for the first point. GPL doesn't mean you have to prepare things on a dish. Nor does it mean you have to open up PRs. It just means that you are legally bound to share. If someone takes away LESS and builds a commercial compiled obstructated closed source app, adds some killer features and it becomes a new great pre-processor everyone has to pay for, then that's a real free rider issue. If someone simply hacks the compiler to do some other things, no one will complain "even if you don't share back". If you want to, you will have to distribute sources or links to those sources. You don't have to advertise or distribute nice sources, just sources.

Issues arise when you are obliged to share sources and how to share them actually. But I'd rather have those small issues than free rider over-takings (think again OS X).

As for your 2nd point: I do agree.
It is not crystal clear even though I'd love LGPL over MIT if one or the other is a better choice. If LGPL creates practical issues that go beyond free-riders not wanting to share back (after all, that is the key difference between free as in freedom and free as in beer), then its an issue and MIT is probably the better option.

**Comment by matthew-dean** [comment]
@ionas Okay, that makes more sense. If I understand you correctly, someone would not have to open source their whole app, they would just need to re-share modifications to Less? That seems fair. I'm just hoping we wouldn't get into a situation where it also means some other restriction we haven't thought of because we're not lawyers, and then we have to spend time discussing new licensing / getting permission again.

So yes, I obviously agree someone shouldn't screw over the Less community, and I want us to be pragmatic about letting people do what they want outside of that, so that they're not afraid to use Less over other solutions. I think striking that balance is important.

**Comment by Synchro** [comment]
@matthew-dean 
>If I understand you correctly, someone would not have to open source their whole app, they would just need to re-share modifications to Less

That is essentially the difference between GPL and LGPL.

**Comment by matthew-dean** [comment]
> That is essentially the difference between GPL and LGPL.

Got it. :-)

**Comment by splitbrain** [comment]
Any progress being made here? Any way the community could help?

**Comment by matthew-dean** [comment]
@splitbrain Is there anything that needs to happen?

**Comment by splitbrain** [comment]
@matthew-dean well... this ticket is still open. I think others here (and in linked tickets) have made clear that the Apache License is problematic when working with other Open Source licenses.

What needs to happen are the following things I believe:

* decide if you want to do a license change
* if yes, decide on a license (LGPL or BSD/MIT)
* once done create a way to ask contributors to agree (eg. using the mentioned license manager tool)
* contact contributors and ask them to agree (explaining the reasons)
* once enough contributors agreed, change the license

**Comment by Riamse** [comment]
I support the LGPL.

**Comment by kryptine** [comment]
I support dual-licensing with MIT because copy left/permissive aside, the Apache License 2.0 (as well as the GNU (L/A/)GPL are too long to include within a distributed script file when requested by a browser.
