### ISSUE TITLE
 no cache for less file data when using browser parser?

### ISSUE THREAD

**Issue by simontang** [less/less.js#1218]
I use new (less.Parser).parse function in browser to parse less file. Most less files use @import to include the config.less file. When I got one less file data in my AMD plugin and parse it, and then less.js always use xhr to get the config.less. I think we can get config.less   via xhr first time and cache it. What can I do now?

**Comment by AnirudhaGohokar** [comment]
This issue is back with vengeance on v.2.7.2. When modifying LESS variables via modifyVars it requests for LESS file again.

With v.2.7.2
![image](https://cloud.githubusercontent.com/assets/5802339/26629214/f2a4b344-461e-11e7-946f-36402b1b79ad.png)

With v.1.4.1
![image](https://cloud.githubusercontent.com/assets/5802339/26629431/001b8ff6-4620-11e7-841f-458ab17a6e3c.png)


Here's a [plunker](http://plnkr.co/edit/ehkpWTcUsOkirH9v9w7v)

**Comment by AnirudhaGohokar** [comment]
Seems like this is broken since v.2.6.0

**Comment by seven-phases-max** [comment]
Or maybe it's [`2.2.0`](https://github.com/less/less.js/blob/3.x/CHANGELOG.md#220) - https://github.com/less/less.js/pull/2054#issuecomment-68624966?
Looking at various browser caching issues/tickets I can see two strictly opposite expectations - first treat non-caching on modifyVars as a bug, other do the opposite (obviously representing two different application areas of the client-script: demoing vs. development).
Related to https://github.com/less/less.js/issues/2970.

**Comment by matthew-dean** [comment]
I did add a feature that cached the compiled styles when using modifyVars at some point (previously it only cached the compiled stylesheet when modifyVars was not used), but I don't think I knew about it actually re-requesting the source file. That shouldn't happen.
