### ISSUE TITLE
Conditional CSS Code

### ISSUE THREAD

**Issue by valllabh** [less/less.js#1293]
How about having something like conditional css code depending upon variable
`````css

@has_theme_support: true;

.awesome-class {
	width: 100px;
	height: 200px;
	margin: 0 auto;
	
	/* Adds theme support if @has_theme_support is 'true'; */
	if( @has_theme_support ){
		background: green;
		color: yellow;
	}
}
`````

**Comment by aukgit** [comment]
Guards are not as good as this. :(

This is a required feature and also present in scass.

+1 for this

**Comment by matthew-dean** [comment]
Just since this comment today was raised a few years after this issue was opened, one thing I will point out that comes to mind at the moment.

Some of the resistance to `@when` in the original discussion is the additional at-rule. However, thinking about it now, it shouldn't be needed.

Considering that these two blocks are equal:
```
.a {
  & .b { color: blue; }
}
.a {
  .b { color: blue; }
}
```
Then these two statements should also be accepted by the parser as equal.
```
.a {
  & when (1=1) { color: blue; }
}
.a {
  when (1=1) { color: blue; }
}
```
If for no other reason than `& when` is syntactically really awkward. Omitting `&` to still imply a selector join with the parent selector has existed all along, so omitting `&` to imply a guard on the parent selector doesn't seem like a leap. Also, block-root functions are now accepted by the parser for use with plugins, so it no longer looks as strange as it might have in 2013.

**Comment by seven-phases-max** [comment]
I don't see any reason to reopen this. After all we already have 

>`when (1=1) { color: blue; }`

Opening a great confusion box just for the sake of two characters economy?

>Guards are not as good as this.

I thought it would not even be worth to comment a random unreasonable comment. Any position should have  something behind it (Otherwise I'd say any conditional code is lame and `ifs

**Comment by matthew-dean** [comment]
> I don't see any reason to reopen this. After all we already have `when (1=1) { color: blue; }`

Errr... no we don't?

**Comment by matthew-dean** [comment]
But it's reasonable that we should. We could just allow it and be done with it.

**Comment by seven-phases-max** [comment]
Wait, until I'll find the feature request it's supposed to ink too (sorry, I accidentaly click enter before finishing it)

**Comment by seven-phases-max** [comment]
So merging this to #2072.

**Comment by matthew-dean** [comment]
@seven-phases-max 

That issue is called "Allow variable redefinition inside guarded self running blocks" and the tangential discussion at the bottom to that issue contained analogous use cases to a select / case and a vbscript iif([ifcond], [then], [else]) function more than just the naked when, although it's perhaps a more logical pickup for the discussion. Buuut... probably it should just be raised as a new issue with just the `when ()` vs `& when ()` question.

**Comment by seven-phases-max** [comment]
>with just the when () vs & when () question.

You can't be serious on this, can you? Because of what exactly? `when` won't not become `if` (see  #2072 for all the reasons) if you remove `&`. So leave it as is and be done with it.

**Comment by matthew-dean** [comment]
Hey, can you tone it down a notch? If you're upset about it, take a moment and look at the reasoning I posted in the new issue. A few things have evolved since these original discussions.

**Comment by seven-phases-max** [comment]
I did not mean to offend or something.
My:
> So leave it as is and be done with it.
was just a reply to:
>We could just allow it and be done with it.

**Comment by matthew-dean** [comment]
@seven-phases-max Okay, tone gets lost in text. In any case, I wasn't terribly attached to this idea, and overall, the existing `@when` proposal is better / more versatile anyway.

**Comment by aukgit** [comment]
I think scss is better than less. It already has if-else. It is really hard and many lines of coding the less. When works but it doesn't full fill the need. Additionally we can make loops in less but language should have it's own feature.

**Comment by matthew-dean** [comment]
@aukgit Use the right tool for the job. If SCSS suits you better, it's better to use that. Sass and Less are very different projects.

**Comment by aukgit** [comment]
@matthew-dean after learning less for months and writing tons less if 'less' community doesn't want to be better then it's loss for both of us. I think that is why bootstrap moved to scss from less (initial reason was faster compilation). Whereas there initial source was in 'less'. Now they write their original source in  scss and then convert it to less (whereas it was the other way around). 

Another thing : 

> **"Write tool for the right job"**

 shouldn't apply here

Less | Scss | Stylus similar projects . Started with one which was popular at the time , now it seems likes doesn't have better features, and the community doesn't want to get improved. 


Thank you for your comments.

**Comment by aukgit** [comment]
![less](https://cloud.githubusercontent.com/assets/4561204/14974738/89fe6c52-111a-11e6-952d-1cea4dd8ce2e.png)

**Comment by seven-phases-max** [comment]
Fanboyish outdated propaganda. It would be a waste of time to argue all of these biased statements.

E.g.:
> There's no way to make really compilacted conditional code.

Yeah, "I need a tool to write my spagetti code" - just like [this](http://stackoverflow.com/questions/23738798). If you write a code like this, indeed Less is definitely not your tool.

**Comment by aukgit** [comment]
I think "less" does 'x' something very different than sass and stylus. All other does similar things whereas 'less' claims it is not a similar kind. :)

**Comment by seven-phases-max** [comment]
@aukgit
>I think "less" does 'x' something very different than sass and stylus.

*Why* it should? See for example [[1]](https://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/) and [[2]](http://blog.scottlogic.com/2013/03/08/less-vs-sass-vs-stylus.html) to find the key differences between designs. So you may don't like the concept but nobody forces you to use a tool you don't like.

**Comment by aukgit** [comment]
Now, I get it. Thank you.  Truly, it is really the most misunderstood language ever. Even javascript is not that misunderstood as Douglas Crockford says. 

People make mistakes in js but there are lot of awareness. For 'Less' it those be first in the web : less.org . 

Thank you.

**Comment by aukgit** [comment]
Wrote a mixen : 

Less: 
```
.if-value-present(@attribute; @value: '') {
    .x (@value) when not (@value = '') {
        @{attribute}: @value;
    }

    .x(@value);
}

.if-value-present-multi(@attributes; @values) {
    .iter(@i) when (@i > 0) {
        .iter(@i - 1);
        // loop

        @attr: extract(@attributes, @i);
        @value: extract(@values, @i);

        .if-value-present(@attr, @value);
    }

    @len: length(@values);
    .iter(@len);
}
.x {
    @var: c1,c2, c3;
    @val: v1, '', 'wddww';
    .if-value-present-multi(@var;@val);
}
.x{
    .if-value-present(content, 'new val');
}
```

CSS Output:

```
.x {
  c1: v1;
  c3: 'wddww';
}
.x {
  content: 'new val';
}
```

**Comment by matthew-dean** [comment]
> if 'less' community doesn't want to be better then it's loss for both of us

I think it's a mistake to assume that "X feature I want isn't supported" == "Less community doesn't want to be better". That doesn't get us anywhere.

There are several discussions on Github to work on improving control flows. In fact, this thread wasn't rejected, it's been merged to #2072. You commented on a closed 3-year-old thread. I had some other ideas that I thought might have made it a bit different from #2072, but was essentially convinced otherwise.

> now it seems likes doesn't have better features

Less doesn't have _more_ features, this is true. This is by design. This is so you can learn Less in a day, and Less's features cover 99% of typical use cases. Sass has a steeper learning curve. Sass had so much feature bloat that they had to build a low-level C-based compiler just to be able to continue to compile it. Which is a great achievement. But not a great testament for something that, at the end of the day, is just making a style sheet.

> Now they write their original source in 'sass' and then convert it to less (whereas it was the other way around).

True, but that's based on multiple factors, and you can ask them what those would be. I personally feel that abandoning Less users is a mistake, since there are a lot of people using Bootstrap in Less today.

At the end of the day, your complaints about the hoops needed to write conditionals are _not wrong_. The examples offered here are simply a bad fit for the language. I suggest you read over the thread in #2072.

**Comment by seven-phases-max** [comment]
(this is actually a bit offtopic, but I'm just wondering)
>```less
@var: c1,c2, c3;
@val: v1, '', 'wddww';
```

And what would be a use of these variables beside calling `.if-value-present-multi`?
Would not it make sens, to use a key/value pair instead, e.g. 
```
@rules:
    c1 v1,
    c3 wddww;
   // no need for c2 since it has no effect
```
More over, what would be a purpose of writing `.x {.if-value-present(content, 'new val')}` if you need just `.x {content: 'new val`}`? And writing `.x {.if-value-present(content)}` if it does nothing?

(Though honesty I did looked at https://github.com/aukgit/WeReviewProject/tree/master/WereViewApp/Content/Less - well, not commenting on anything except just one thing: to save your time consider throwing away ancient libs like `elements` and `lesshat` - and use `autoprefixer` instead).
This is usually how most of "feature requests" come in ["XY Problem"](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

**Comment by matthew-dean** [comment]
@aukgit You should be able to collapse those mixins easily.

https://gist.github.com/matthew-dean/e617bc1f71528843ef9fa73d70427bcf

**Comment by aukgit** [comment]
Thank you @matthew-dean for taking your time and helping me out. :) I am great full to you .

:)

**Comment by jslegers** [comment]
> I think 'sass' is better than less. It already has if-else.

Both languages had their own issues. 

Their lack of dynamic imports - [and their reluctancy to implement it](https://github.com/sass/sass/issues/739) - is the main reason I'd like to switch from Sass to Less. Less has had this feature for years!

The lack of traditional [control structures](https://en.wikiversity.org/wiki/Control_structures) (like the FOR-loop or IF-ELSE-statements) and the cringe-worthy syntax is what prevents me from making this move.

I feel stuck between a rock and a hard place...

**Comment by seven-phases-max** [comment]
@jslegers Same comment as in #249. Less has various forms (more and more in newer version) of conditional strictures since v1.x.

**Comment by jslegers** [comment]
@seven-phases-max

I'm aware of [guarded mixins](http://lesscss.org/features/#css-guards-feature) as an alternative to IF-statements and [recursive mixings](http://lesscss.org/features/#loops-feature) as an alternative to loops in Less. But that's all I've been able to find in the docs about control structures in Less. And as someone with programming experience in many languages, I find their syntax confusing and - to be honest - quite cringe-worthy. 

If there's other control structures besides those that are worth mentioning, I haven't been able to find them in the docs.

Anyway, something like ...

````scss
a {
  @if $time == morning {
    color: red;
  } @else if $time == afternoon {
    color: blue;
  } @else {
    color: grey;
  }
}
````

... or something like...

````scss
  @each $author in $list
    .photo-#{$author}
      background: image-url("avatars/#{$author}.png") no-repeat
````

... or this...

````scss
@for $i from 1 through 8 {
    $width: percentage(1 / $i)
    .col-#{$i} {
        width: $width;
    }
}
````

... is far more readable and far more elegant in my opinion than having to write something similar with guarded mixins or recursive mixins. 

The lack of such statements and Less's overall less readable syntax are the two main reasons I'm reluctant to even consider Less for one of my projects.

And considering Sass has about 5x the amount of users as Less these days, I'm clearly not the only one who feels that way.

![](https://blog.keycdn.com/blog/wp-content/uploads/2015/09/sass-vs-less-poll.webp)

**Comment by seven-phases-max** [comment]
@jslegers For your examples - try to learn what's already available before posting them. 
For the rest (popularity and so) - there's no point in discussing something in such oversimplified way (Stylus has all of this and so what?), besides Less was never declared to replace other CSS-preprocessors nor to become their clone. And finally, the most common mistake is to think the popularity of something is the primary and the only goal of that something authors.

**Comment by jslegers** [comment]
> try to learn what's already available before posting them.

Try to document better or to point people directly to what they're looking for, if they aren't finding it.

> there's no point in discussing something in such oversimplified way [...] And finally, the most common mistake is to think the popularity of something is the primary and the only goal of that something authors.

FYI, I never implied that popularity is a strong indicator for quality. In fact, quite often it's the other way around.

Still, if you look why people move from Less to Sass, [it's pretty straightforward](https://hugogiraudel.com/2012/11/13/less-to-sass/)...

**Comment by seven-phases-max** [comment]
Personally there I can't see anything but the usual "I want my PHP spaghetti" (see posts about wrong tool above), not even counting its 2012 (I already hinted that most of these examples goes pretty compact in modern Less, but it seems you don't want to wake up). 
But never mind, usually I only argue a clear misinformation, discussions of personal opinions of why something do or does not happen are totally out of my interest.

**Comment by jslegers** [comment]
> Personally there I can't see anything but the usual "I want my PHP spaghetti"

It seems to me that using Less instead of Sass makes your code inevitably look like "PHP spaghetti" (if you think PHP is the epitome of spaghetti code, you obvious never programmed in SAP) as soon as you want to do something more complex than basic variables and mixins, but I'm willing to consider that I'm wrong here.

> I already hinted that most of these examples goes pretty compact in modern Less, but it seems you don't want to wake up

Then why not make an effort to wake me up and give me a source or two that could relieve me of my ignorance?

There's little I find more exciting than someone proving me wrong. In my experience, that's the best way to grow...
