### ISSUE TITLE
Couldn't load imported Less file 1) with a period in it's name and 2) without extension

### ISSUE THREAD

**Issue by lmeurs** [less/less.js#1297]
Hi,

 I just upgraded from v1.3.0 to v1.3.3 and ran into an issue with importing a Less file named `chained.banner.less`. I always import Less files without an extension, ie. `@import "chained.banner";` and apparently v1.3.3 guesses that `.banner` is the extension.

Swapping the period in the file name for a dash (ie. `chained-banner.less`), adding a non a-z character to the 2nd part of the file name (ie. `chained.banner123.less`) or adding the extension to the import (ie. `@import "chained.banner.less";`) seemed valid workarounds.

**Comment by r-wettstaedt** [comment]
I am still encountering this issue with less 2.7.3. You can easily test this as well:

> fileA.less
```less
@import (less) 'fileB.min
```

> fileB.min.less
```
* { color: red; }
```


Executing this command
```bash
lessc fileA.less out.css
```
results in this error
> FileError: 'fileB.min' wasn't found. 


Unfortunately, something similar to this got shipped by a 3rd party plugin that my system relies on, so I cannot change that by myself easily. Would be great if this could be fixed

**Comment by seven-phases-max** [comment]
Less is not supposed to auto-append `less` extension in this case because the name already looks like having a one (= `min`).
See http://lesscss.org/features/#import-atrules-feature-file-extensions for more details.
The proper import should be:
```less
@import 'fileB.min.less';
```
in this case.

Note the `(less)` option is implied by default, its implicitly required only when the extension of the imported file directly assumes another importing behaviour (e.g. `foo.css`). And neither of importing options affect the auto-appending of extensions, i.e. it's always:
`foo` -> `foo.less`
`foo.bar` -> `foo.bar`
`foo.css` -> `foo.css`
etc. and so on regardless of any options after the `@import` statement.

**Comment by r-wettstaedt** [comment]
@seven-phases-max, thanks for your explanation. I guess I gotta talk to the plugin developers then.
