### ISSUE TITLE
--include-path does not respect absolute paths

### ISSUE THREAD

**Issue by bdkjones** [less/less.js#1409]
Hi guys,

Bryan here. The CodeKit guy. I'm using the new `--include-path=` option to pass folders where lessc should look to resolve @import statements like this:

    --include-path=/Users/bdkjones/myfolder:/Users/bdkjones/documents/someOtherFolder:/Users/bdkjones/documents/subfolder

Something is not working, however, because lessc can't resolve imports that are in those locations. I took a look at the source (briefly) and noticed that the `--include-path` option takes into account the current working directory in some fashion, which is what's breaking this, I think.

The current working directory is not always going to be set to what you think it is if lessc is being run as part of a bundled app, build script, or other tool. That assumption is really only safe if lessc is being run from the command line, by the user, directly. 

Using the -I flag works correctly. Therefore, I have an either-or request:

1) Change `--include-path` to work correctly without CWD

OR 

2) NEVER deprecate the -I flag. 

Thanks!

**Comment by SomMeri** [comment]
I just tried it on windows and both absolute path and relative path in `--include-path` worked. I guess that problem was fixed in the meantime by whoever added [this line](https://github.com/less/less.js/blob/577afc35bc1a9df71066200254334a95c0f5eb00/bin/lessc#L146).


If it still does not work, please reopen.
