### ISSUE TITLE
Variable selector "string" improperly parses comma

### ISSUE THREAD

**Issue by scottgit** [less/less.js#1421]
This [StackOverflow question](http://stackoverflow.com/questions/17662644/group-css-selectors-in-less-for-pseudo-class-use) lead me to test what I thought would work, but failed. Namely, this example:

```
@inputs: input[type=text], input[type=email], input[type=password], textarea;

@{inputs} {
  &:focus {/*properties*/}
} 
```

Did not produce what was expected, as it failed to recognize the commas as separators of individual selectors. So instead of this **expected output**:

```
input[type=text]:focus,
input[type=email]:focus,
input[type=password]:focus,
textarea:focus {
  /*properties*/
}
```

It produced this **unexpected output** of just adding the `:focus` on the end of the whole variable value:

```
input[type=text], input[type=email], input[type=password], textarea:focus {
  /*properties*/
}
```

If the variable interpretation for selectors uses the same algorithm as when a variable is in a string, I can see "why" it is doing it that way, but it would seem to me that, at least for the case of the `,` in CSS, the variable interpretation needs to recognize it is dealing with a selector at that point, and should then take the next step and parse each of the commas to separate selectors, so that all nested uses of `&` will attach to all the appropriate selector strings.

**Comment by erquhart** [comment]
@seven-phases-max so ReadyForImplementation means this is coming, but Low Priority means don't hold your breath. Any idea if this will happen in the near future?

**Comment by seven-phases-max** [comment]
`ReadyForImplementation` only means it's just decided that it *may* be in if someone implements it (not necessary coming soon or ever at all if nobody finds time to implement it).

**Comment by calvinjuarez** [comment]
Something to think about:
http://dev.w3.org/csswg/css-extensions/#custom-selector

**Comment by matthew-dean** [comment]
I think all that's needed here is for Less to treat comma-separated lists equally. A variable that holds a list should be expanded with ```&``` in the same way as a list of selectors. In other words, we don't actually need to know that the list contains valid selectors in order for this to work, AFAIK.

**Comment by matthew-dean** [comment]
Elevating priority because of #2964.

**Comment by matthew-dean** [comment]
I have a work-in-progress here: https://github.com/matthew-dean/less.js/tree/bugfix-1241 but the parsing is way more complicated than I thought when I started.

Basically, the normal evaluation pattern of Less is stuff gets evaluated and then returns an evaluated copy of itself. In this case, the variable reference is added as an `Element` in a `Selector` in an array of selectors inside `Ruleset`. This can be re-parsed at eval-time as selectors, but then you have to correctly re-organize the tree so that what was thought to be an element is actually an entire list of selectors, so you need to merge those selectors into the top-level selectors BUT they may NOT be selectors (and may be elements), so they need to be preserved and just evaluated.

If someone wants to take the work on that branch and run with it, be my guest. I think that's all the time I'll have for it.
