### ISSUE TITLE
Allow Semicolon as Function Argument Separator

### ISSUE THREAD

**Issue by matthewwithanm** [less/less.js#1505]
Since semicolons are the recommended way to separate arguments for mixins, it seems to me that it would be a good idea to allow them to be used for functions as well.

**Comment by matthew-dean** [comment]
With the merge of ```@plugin```, this request makes sense. People may reasonably want to pass in CSS lists as an argument to a custom function without having to resort to hackish escaping.

**Comment by matthew-dean** [comment]
Should I remove the "Consider Closing" tag? (Maybe consider leaving open?)

**Comment by matthew-dean** [comment]
See #2270 for a real use-case example where semi-colon separaters in a user-defined function would be necessary, or at least desirable. (The "each" example passes in a CSS list.)

**Comment by chharvey** [comment]
just a thought…
maybe keep css functions (such as `linear-gradient()`) per usual with comma-separated arguments, but allow Less functions **that aren't present in css** (such as `fadeout()` and `mix()`) to have semicolon-separated arguments. in addition to being consistent with using semicolon-separated arguments in mixins, this would also help make the distinction between css functions and Less functions.

**Comment by matthew-dean** [comment]
@chharvey What you say sounds logical, but wouldn't actually be easily achievable. In the first stage of evaluation, Less is only parsing your code. Evaluation of functions only happens after you have a complete tree. Which makes sense, if you think about it, because a custom function can receive an entire ruleset, spanning multiple lines and property / value pairs (and arguments).

When functions are evaluated, Less.js checks to see if there's a matching function name within the current scope. If not, it outputs the function as is. When it writes CSS, the operation happens in reverse, with arguments output with comma separators.

However... I think mixin nodes are already marked as having comma or semi-colon separators, so maybe the same could happen for functions. So that: if a Less function is not found during evaluation AND the function has semi-colon separators, then Less could throw an error.

**Comment by seven-phases-max** [comment]
> this would also help make the distinction between css functions and Less functions.

The initial idea was actually *to not* have distinction between two (just because CSS functions as well as Less are not something set in stone). So parser does not and cannot have any distinction between those. More over some CSS functions (e.g. `rgba`) actually handles via Less functions and most Less functions (e.g. `contrast)  fallback to CSS functions.

**Comment by matthew-dean** [comment]
@seven-phases-max Looks like we commented at the same time. The parser wouldn't know if they're valid, but could mark the type of separator.

**Comment by seven-phases-max** [comment]
>So that: if a Less function is not found during evaluation AND the function has semi-colon separators, then Less could throw an error.

Does not look like something useful since it can't cover 0..1-parameter functions anyway. Besides, some (radical purists like me) not just do not favor `;` as separators (thus do not share *that* docs sentence) but actually whenever possible recommend strictly the opposite ("never use `;` unless it's unavoidable") :neckbeard:. So as a user  I definitely would not want to be forced to use `extract(foo bar; 1)`.

So to target *that* problem (e.g. throw a error for `extract(foo bar, 11)` instead of passing as-is), could not we just have a compiler option?

**Comment by matthew-dean** [comment]
No, no, not forced. Never forced. The request is actually just as an option. And you misunderstood. Less would not throw an error for `extract()` with a comma. Not at all. I was suggesting it could throw an error if a) semi-colons were used, b) the function was not found. But such a thing is not a necessity. The feature request is just semi-colon as an option, like it is for mixins. It seems legit.

**Comment by seven-phases-max** [comment]
> I was suggesting it could throw an error if a) semi-colons were used, b) the function was not found.

Yes, but if I'd want to use that nice new nice feature (throw a error if Less function is not found) I *had* to use semicolons (and coud not get the same with commas) :) But never mind, I get what you mean in general.

**Comment by matthew-dean** [comment]
Ohhh okay, now I get what _you_ mean. Ha, yes. This is true. Which is probably why we should pass on that idea. I was just spitballing how Less could distinguish Less/CSS functions, as @chharvey was suggesting, but yeah, it's probably better to avoid that.

**Comment by matthew-dean** [comment]
Optional semi-colons in functions are supported in Less 2.7.0.
