### ISSUE TITLE
Extends on non existing class throws no error.

### ISSUE THREAD

**Issue by nextgenthemes** [less/less.js#1618]
Using 1.5.0-b4

```
.test {
	&:extend(.idonotexist all);
}
```

Less just compiles silently without mentioning that the `.idonotexist` class not exists and therefor nothing can be extended. I think there should be a error of some sort if this happens.

**Comment by ddprrt** [comment]
I'd have a PR ready if you could show me how to throw a warning ;-) (I can throw errors, I'm good at that :smirk:)

**Comment by lukeapage** [comment]
I started work on it

https://github.com/less/less.js/tree/extend-warnings

Thats the bare bones but i think i remember som problem (maybe it is
incorectly warning on extends extending an extend - sorry dont remember).

Please feel free to finish the work, just comment here if you are picking
it up.

**Comment by ddprrt** [comment]
I took a look at your code and found the following:

```
.a {
	&:extend(.b);
}

.c {
	&:extend(.a);
}
```
yields `extend ' .b' has no matches` two times. I think that's because `.c` also wants to extend from `.b`. Maybe that's the issue you're referring to. 

I guess I'll give it a shot. Your implementation is roughly the same as I did (expect yours being more sophisticated), so I think I'll find my way around
