### ISSUE TITLE
Specify variables on parser instantiation

### ISSUE THREAD

**Issue by rumkin** [less/less.js#1980]
Add predefined variables to parser like this:
```javascript
var parser = new (less.Parser)({
    filename : ['style.less'],
    variables: {
       'active-color' : '#03f'
    }
});
````

**Comment by lukeapage** [comment]
this issue is unclear and I think both elements have been addressed
1. in v2 we now use less.render and that takes the modifyVars argument
2. in the soon to be released verison of less, the browser does not cache when modify vars is not loaded.

I'd suggest possibly a new more specific issue if there are still issues after the latest release.
