### ISSUE TITLE
Onetime/Async Compiling? [Suggestion | Idea]

### ISSUE THREAD

**Issue by ghost** [less/less.js#2118]
Hey Guys, I'm working with LESS for a bit now, and now I got a big less file with some resource-unfriendly mixins.

Now when I load my Page it freezes obvíously and that takes me to my Question:
Isn't it possible/better to complile the LESS to CSS and save it as CSS-File and link that instead of adding the Style-inliner? With that you can have huge LESS-Files, but you only need to compile it once instead of everytime when someone loads the Page.

What my Idea is: You are entering the Path to the LESS-File (or detect it from the head) and you give it a compile-Path. In here there's a copy of the Origin-LESS-File and the compiled CSS-File.
When someone loads the Page, you check if the Origin-LESS-File is the same as the Copied-LESS-File to check if it has updated. If so copy it over again and compile it.
With something like that it would only freeze it for the first Person.

I know you switched to Client-Side-Compiling a time ago, but it's sometimes Inefficient.
Otherwise isn't it possible to compile it Async? I took a look with Web-Workers, but I'm not a pro Web-Dev so I have no clue how to do usefull stuff with that :/

**Comment by kuus** [comment]
anybody interested in trying to make work less in the browser with web workers? Obvious benefits:
 - faster
 - doesn't freeze UI while compiling

**Comment by matthew-dean** [comment]
It's possible to do, but it would involve having a script on the server to send the compiled file back to, in order to cache it for future requests. If the web server is involved anyway, you might as well compile/cache at the web server, if you want to only compile at the time of request.

Aaaaand... if you are compiling on the server, than you might as well compile BEFORE the first request, when your source files change, so that the first person to hit the page after .less changes isn't penalized.

This is where the logic of compiling client-side breaks down. In truth, we support client-side compiling for historical reasons, but it's hard to argue any practical reasons to use it. For testing? Maybe. But if you're not going to use it in production, then it's hardly a comparable test for your page.

However, if you don't have any access to a web server (e.g. depending on platform, sometimes you can insert style blocks but not configure the web server), I can see needing another option. So while Less provides you solution in that case, it's not a particularly good one. A better one would probably be a "compiler-as-a-service", a web service that compiles your .less files for you, which, to my knowledge, doesn't exist.

**Comment by kuus** [comment]
@matthew-dean I guess you replied mainly to @prefixaut, what I was asking / proposing was to improve less in the browser using [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/basic_usage), a practical reason is for instance a css live editor where there are no ways to run the compiler server side. Should I open a separate issue?

**Comment by matthew-dean** [comment]
@kuus As a performance improvement, I think that's a valid request. Yes, since @prefixaut mentions 2 proposals in this issue, that being one of them, it might make sense to open a separate issue for a web worker performance improvement (if support exists in that JS environment), if that issue doesn't exist already.
