### ISSUE TITLE
Feature: Significant Whitespace?

### ISSUE THREAD

**Issue by ghost** [less/less.js#2170]
I have a dream, that my even-LESS file would read something like:

```
.navbar
  display:block;
  .item
    float:left;
    text-decoration:none;
    &:hover
      text-decoration:underline;
```

Thoughts?

**Comment by billymoon** [comment]
Would it be easy to pre-process `even-less` into `less` instead of replacing the `less` parser, so that it is not necessary to maintain a fork of the main parser...

Would it be possible/easy to implement this as `plugin`, so as not to interfere with simplicity and core objectives of existing project, yet remain tightly integrated?

(starting brutally hacking proof of concept together here: http://stackoverflow.com/questions/28073693/preprocess-less-to-permit-whitespace-sensitive-syntax)
