### ISSUE TITLE
For some reason new iOS8 Safari browser doesn't compile lessjs, and you have to precompile it to CSS first to apply the styles.

### ISSUE THREAD

**Issue by admix** [less/less.js#2196]

**Comment by KevinEverywhere** [comment]
SOLVED! I hope this might help others. I use less for calculating sizes in resize and reorientation, as well as initial values. Because I use less.modifyVars, and I noticed that after reorientation, the layout worked, I called the function that I assigned to resize/reorientation just after rendering. This did the trick! At the moment, I've used CSS to hide, then reveal the Body, so that no Less warning text is visible. The original issue is still present at the initial rendering, but after a short timeout, the content works as it should.

http://bob-angular.herokuapp.com/

**Comment by brantkings** [comment]
I don't think this is solved at all!

@KevinEverywhere, waiting for a timeout after loading the document is not an optimal solution, plus what exactly that function that you assigned to resize/reorientation just after rendering does?

I rely on cheaper web services, and as node.js is not a possibility (and still need fast dev) I need client-side less for a while.

**Comment by knyttl** [comment]
I am having the same iOS/Safari issue on http://overtone.cz. The strange thing is that on some iOS devices it works correctly, on some others I am getting random compilation errors even though all the devices have the same iOS/Safari versions.

Using: Leaner CSS v2.5.1

I am including screenshots to demonstrate the random behaviour when reloading the site.

![img_0070](https://cloud.githubusercontent.com/assets/401107/9269667/1ec41dba-426c-11e5-912f-d7caa8a13f7d.PNG)

![img_0071](https://cloud.githubusercontent.com/assets/401107/9269672/287b8b68-426c-11e5-83f0-8c285d935d35.PNG)

![img_0072](https://cloud.githubusercontent.com/assets/401107/9269675/2d38fc80-426c-11e5-8baa-7bd84f0e46b6.PNG)

**Comment by knyttl** [comment]
Would you please reopen the issue or shall I create a new one? This one is obviously not fixed.

**Comment by bruno-amaral-diamond** [comment]
You can keep on this topic. I agree, it was not fixed. We left this Less
approach due to its lack of support on iOS8.

With the latest version of Less we had some issues and strange behaviour on
Internet Explorer.

Bruno Amaral

GENERAL MANAGER • +351 919 215 195 • brunoamaral@diamondbybold.com
[image: Logo][image: Icon Twitter] <https://twitter.com/diamondbybold>[image:
Icon Facebook] <https://www.facebook.com/diamondbybold>[image: Icon
Linkedin] <https://www.linkedin.com/company/diamond-by-bold>[image: Icon
Google+]
<https://plus.google.com/u/0/b/106843947582804064792/106843947582804064792>[image:
Melhores empresas para trabalhar][image: Empresa de excelencia]

LISBOA: Av. 5 de Outubro 72, 7-D, 1050-059 • +351 926 333 186

DIAMOND BY BOLD • Design, Web & Digital Marketing • www.diamondbybold.com
<http://www.diamondbybold.com/?utm_source=signature&utm_medium=email&utm_campaign=BOLD>

**Comment by knyttl** [comment]
Follow-up here: https://github.com/less/less.js/issues/2668

**Comment by KevinEverywhere** [comment]
@brantkings  @knyttl  @bruno-amaral-diamond  The workaround that helped me use client side LESS in iOS Safari and other browsers is one where a function defines less variables through less.modifyVars. In this case, simply cast the variables--even as empty variables; and then provide their definition through the modifyVars function. The greatest problem that I regularly come across is accessing variables before they have been defined or scoped. At least, you might want to try and see if this helps.

**Comment by knyttl** [comment]
Could you provide an example? Thanks!
