### ISSUE TITLE
beautify less code

### ISSUE THREAD

**Issue by thisguychris** [less/less.js#2202]
Is there a an equivalent cli tool for less css?  The reason I asked is currently we are using sass-convert to beautify our sass, we're moving to less for future projects.

Also beautifying code is just one thing, but it also normalized our code which is good for collaboration.  The developers don't need to agree to whatever style since it will be reformatted upon by save.  We are using sassbeautify plugin which uses sass-convert for beautifying options.

So as soon as you save sass it reformats it on the fly.  So git diffs are easy to see on the commits as well.

**Comment by seven-phases-max** [comment]
Probably this should be merged to #1271 (since to "beautify" Less using `less.js` itself, in first place there're should be a way to output Less... And if it's not about using `less.js` than this is simply out of this repo scope).

**Comment by matthew-dean** [comment]
Why not just use an IDE that supports code coloring for Less? I'm sure *cough* someone *cough* makes one.

**Comment by oliverjanik** [comment]
The whole point of doing formatting tool by less project is so that IDE's can use that standard formatting and not recreate their own incompatible versions.

I wanted to write an extension for VsCode to autoformat less and well this is the first place I looked.

The less compiler understands AST of less, therefore this is the best place to create a nicely formatted output of that AST.
