### ISSUE TITLE
How to trigger sync and async imports

### ISSUE THREAD

**Issue by jhnns** [less/less.js#2325]
How does less decide to call `loadFile` or `loadFileSync` of the current `fileManager`? According to [this code](https://github.com/less/less.js/blob/94a6501adee79db3aa91d2b62cd066db784d7be1/lib/less/environment/environment.js#L36) it requires an `isSync`-parameter to be set. But a short search for a call to [`getFileManager`](https://github.com/less/less.js/search?utf8=%E2%9C%93&q=getFileManager) reveals that this option is only used by `lib/less/functions/data-uri.js`.

Is it possible to set this option explicitly when calling `render()`?

**Comment by lukeapage** [comment]
Its done here

https://github.com/less/less.js/blob/32dbbee247f76af00eb7577053eccad2ee5f6110/lib/less-browser/file-manager.js#L61

Its because that option is ignored by less core and is specific only to the browser. So the browser always gets called async and may depending on options use a sync or async mechanism to get the file.

I can see how that's confusing. Is it causing a problem?

One thing I see immediately is that it will onyl be effected by the options at page load, so if it is set afterwards or passed in as an option it will be ignored..

**Comment by jhnns** [comment]
Well, probably i have to explain my use-case:

I've written a [less-loader](https://github.com/webpack/less-loader/blob/3affb7b98f72a400c3978a74c3219358fd534e44/index.js) for [webpack](http://webpack.github.io/docs/). Since webpack has an own resolving mechanism I'm using a plugin to hook into less' file resolving via a file manager.

Webpack supports sync and async loaders but I haven't found a way to tell less to render all files sync or asynchronously. Currently it always calls `loadFile`. Thus I used a [dirty hack](https://github.com/webpack/less-loader/blob/3affb7b98f72a400c3978a74c3219358fd534e44/index.js#L73-L84) to call `loadFileSync` when a synchronous compilation is requested. Luckily less works synchronously when the callback is called synchronously (which shouldn't be done under normal circumstances of course).

**Comment by lukeapage** [comment]
I see...

**Comment by lukeapage** [comment]
I think we should move an async option to be on the less context, then use that to determine which call to make as you suggest. It may need a few changes to the browser file manager, but I think it will be a good refactor.

**Comment by jhnns** [comment]
Cool!

There is just one problem: It is very unusual to do something synchronously while accepting a `callback` (as the `render`-function does). You're suggesting a `sync`-option like this:

```javascript
less.render(
    input,
    { ... sync: true ... },
    function (err, result) {
    }
);
```

?

Imho it's weird to have the callback being called synchronously. I'd expect an api like this:

```javascript
// async
less.render(input, option, callback);

// sync
var result = less.renderSync(input, option);
```

**Comment by lukeapage** [comment]
Yes you are right, that's better.

**Comment by kwketh** [comment]
+1
It seems this is also very useful to consider implementing `renderSync` to not restrict code execution in the callback only. In the callback scope many methods such as `console.err` or `throw new Error()` or deliberate JavaScript error will not print anything to the console, only stop the code execution, potentially leading to bugs that cant be traced. I would imagine this behaviour should not happen.

In my particular case `renderSync` would be used in a command-line utility and rather than controlling the callback flow using promises to ensure all output and errors are printed in order each time, I would rather just use renderSync and not have to worry about it.

**Comment by seven-phases-max** [comment]
(Not denying the issue itself, but just ensure it won't get even more weird the it is):

>Imho it's weird to have the callback being called synchronously.

This an exaggeration... In [this line](https://github.com/webpack/less-loader/blob/3affb7b98f72a400c3978a74c3219358fd534e44/index.js#L38) of the code you're not assuming the config is set asynchronously, are you?
Callbacks are just a callbacks, by themselves they have nothing to do with sync/async stuff.

**Comment by jhnns** [comment]
Ok, than we need to talk about the term `callback` :wink:.

I know, some do call functions passed to `forEach` a `callback` (like [MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)). I wouldn't call it so, because for me a callback is something that is called when a task has been finished.

And if the callback follows node's error convention with the first argument being `null` or an error, than there are [good reasons](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony) to *always* call it asynchronously.

**Comment by seven-phases-max** [comment]
>I know, some do call functions passed to `forEach` a callback`

Someone is just using too much `node` ;) [Everybody](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.18) name this thing a "callback". So if one is about "a callback function called when a task has been finished" it's no more no less than "asynchronous callback". 

But never mind, sorry, I did not mean to sound like a CO and start this purely linguistic debate (just wanted to ensure we speak the same language and [the docs](http://lesscss.org/usage/#programmatic-usage) actually mention `less.render` is synchronous).

**Comment by seven-phases-max** [comment]
P.S. Just to clarify more:

@kwketh 

This `less.render` form was there for years, you can't just take and change out of nothing to break zillion snippets out there.

**Comment by kwketh** [comment]
@seven-phases-max 

Many thanks for your answers, they are all helpful. I agree with you with all your points regarding callbacks. I had a very brief look at the `less.js` `.render` code and you are right, the form it is written it all revolves around the callbacks and doesn't seem neither easy or reasonable to have `renderSync`.

My issue is different but somehow related (https://github.com/less/less.js/issues/2546). It would seem `renderSync` feature would resolve my issue but it isn't the actual solution.

Do you mind having a quick look? I would really appreciate.

Thanks.

**Comment by jhnns** [comment]
> Someone is just using too much node

Well, that's true :grin: 

But node's callback convention is well-established. I'd assume the callback to always be called asynchronously in this case.

In addition: How are errors handled when there was an error? Is it thrown (like most sync APIs) or passed as argument to the callback?

It's just that the current API is ambiguous (at least imho)

**Comment by Aarilight** [comment]
Is there a `renderSync` yet? If not, is there a workaround for a synchronous render?

**Comment by jhnns** [comment]
Is this feature actually implemented? Is there any documentation? I can only find the `async`-option.

**Comment by Aarilight** [comment]
Idk if it's actually supported, but I know what I did works for me currently, so.... \*shrug\*

**Comment by sylvainpolletvillard** [comment]
@Aarilight thank you very much, your code helped a lot

This synchronous callback behaviour is really counter-intuitive :confused:

**Comment by lapanoid** [comment]
@Aarilight it don't work for me=(
I tried 
```
less.render(css, {sync : true}, (e, result) =>{
    	if(e) {
	     console.error(e)
	}

    	output = result;
    	return result
    });
```

and logged https://github.com/less/less.js/blob/master/lib/less/render.js
```
            console.log('1')
            this.parse(input, options, function(err, root, imports, options) {
                console.log('2')
                if (err) { return callback(err); }

                var result;
                console.log('3')
                try {
                    console.log('4')
                    var parseTree = new ParseTree(root, imports);
                    console.log('5')
                    result = parseTree.toCSS(options);
                }
                catch (err) { 
                    console.log('6')
                    return callback(err); 
                }

                console.log('7')
                callback(null, result);
            });
            console.log('8')
```

And I see 1, 8 and then 2,3,4,5,6,7 for some files

**Comment by matthew-dean** [comment]
-1 to splitting render into ```render``` and ```renderSync```. It's a Node.js convention that is awkward. And it doesn't allow sending a sync option to grunt / gulp / accord or other workflows integrated into less that pass in a JS object to a designated function. IMO it's fine to pass in an optional callback when using an async option.

Another option: what I've seen libraries start to do is actually return a promise in either case. Then, all that changes between sync / async is when the promise is fulfilled, but the code handling the result is exactly the same.

**Comment by seven-phases-max** [comment]
And btw.:
>`{sync : true}`

There's **no** such option.

**Comment by jonschlinkert** [comment]
> -1 to splitting render into render and renderSync. It's a Node.js convention that is awkward.

Isn't that a completely subjective viewpoint? IMHO combining async and sync in a single function is (with few exceptions) a terrible anti-pattern. It creates code that is cluttered with conditional statements, is harder to maintain and is even more confusing for the user than a clearly defined and documented function that does one thing well. just my 2c

**Comment by matthew-dean** [comment]
> Isn't that a completely subjective viewpoint?

Yes? A viewpoint, by definition, describes, literally, a point of view, which is held by the subject. Ergo: it is subjective. "Awkward", while it could describe something that has an erratic behavior, or something that is cludgy and "un-graceful" (which are also subjective), in this context is more commonly used to describe an emotional reaction. And since code does not have feelings, it's generally understood that the feeling of awkwardness is felt by the developer. Feelings, also, by their nature, are subjective.

So, I'm not sure if a "subjective viewpoint" is an observation intended to invalidate an opinion by describing something by what it obviously is. Either way, you're welcome to feel differently. And I don't think the fact you feel a certain way invalidates those opinions. Some people may like the {name}() / {name}Sync() convention. Alright then. Cool.

Regardless, my other point is not subjective. That is, that Less is used in build processes that might need to update if a function is split. For instance: Accord (https://github.com/jenius/accord), which I currently use for one project, abstracts out different compilers into a single API, and typically passes in an object to whatever function that engine requires. So, it's probably not a huge deal to switch which function is used based on the Less options a developer specifies, but I'm not sure how many libraries that would affect. It's just something to be aware of.

So, subjectively, in an opinion held only by myself and no other individual that I am aware of at this time, yes, I prefer one function for compatibility reasons. But, if it were written today, it would probably return a Promise in either case, since it would normalize the return and normalize error handling. Might be something to consider for the future.

**Comment by jonschlinkert** [comment]
> I don't think the fact you feel a certain way invalidates those opinions. 

I don't have any feelings about it. I was just stating the **fact** that conditional code to determine if a function is sync or async makes it more complicated and harder to maintain. Not an opinion.

**Comment by jonschlinkert** [comment]
Btw, have you heard the news? They created another kind of view point, called "objective". Might be worth looking into.

**Comment by matthew-dean** [comment]
@jonschlinkert Jon, c'mon. What are you even talking about? None of those things are facts as those are experiential. And calling something fact v. opinion or objective v. subjective has nothing to do with what people are choosing to note in a particular issue about which things should be considered for a decision, that they deem of importance. The deeming of importance is subjective.

All of this is off-topic. Are you having a bad day? What's with the additional jabs? There's no need to make an issue personal in order to simply render an opinion about it. We're talking about a function here.

**Comment by matthew-dean** [comment]
Don't really want to bite this bait, but FWIW, an objective viewpoint is a term used to describe a storytelling device in which the actions and setting are described but not a character's inner thoughts and feelings. It's not actually a viewpoint that's held by an individual. Sometimes people say a viewpoint could be "more objective", which means to view other opinions with less bias.

Or in this case, fewer personal attacks, please Jon.

**Comment by jonschlinkert** [comment]
Good grief, I'm not feeling anything about this at all. I was being facetious, I figured you were too. (I thought I knew you enough to assume that you were being humorous and not sarcastic with your detailed description of what "view point" means).

In any case, that my last point was opinion is like saying that it's an opinion that running 10 miles requires more energy than running 1 mile. Sorry, but it's not opinion, it's math. Whether or not it's worthwhile or useful to do one pattern over the other, despite the code debt, is another matter. I agree that part is more subjective.

**Comment by jonschlinkert** [comment]
> Or in this case, fewer personal attacks, please Jon.

Are we having the same conversation? I'm at a loss about what you're referring to. If I did make a personal attack unintentionally, I'm sorry. Can you point it out, specifically?

**Comment by seebigs** [comment]
As of now, adding `syncImport: true` to my options fixed this for me.

(It's not in the documentation... I was just lucky enough to stumble across it in the source code)

**Comment by michail-peterlis** [comment]
> 
> 
> Is there a `renderSync` yet? If not, is there a workaround for a synchronous `render`?
> 
> Edit: Nvm. For any future person who stumbles upon this, this is what I did:
> 
> ```
> less.renderSync = function (input, options) {
>     if (!options || typeof options != "object") options = {};
>     options.sync = true;
>     var css;
>     this.render(input, options, function (err, result) {
>         if (err) throw err;
>         css = result.css;
>     });
>     return css;
> };
> ```

Unfortunately seems this does not work anymore...
