### ISSUE TITLE
Allow LESS Refresh to be Disabled onDomReady

### ISSUE THREAD

**Issue by jlukic** [less/less.js#2327]
Currently I'm using a custom build of less.js to snip out the call to ``less.refresh`` on page load.
https://github.com/less/less.js/blob/master/dist/less.js#L78

It would be useful if this was a built in less setting. 

Something akin to:
```javascript
window.less = {
  onReady: false
};
```

This would be useful when you have ``less`` stylesheets included on page load, but only want them parsed programatically.

**Comment by lukeapage** [comment]
that makes sense

**Comment by jlukic** [comment]
@lukeapage 

I tried out the setting ``onReady: false` in `2.2` and received an error 
```javascript
TypeError: less.sheets is undefined
for (var i = 0; i < less.sheets.length; i++) {
```

On these lines
https://github.com/less/less.js/blob/master/lib/less-browser/index.js#L152

Most likely this is because less.registerStyleSheets is called inside the options.onReady conditional.
https://github.com/less/less.js/blob/e9b227c9ac03252aca0ab0cda1e3184a76862855/lib/less-browser/bootstrap.js#L21

My question is: Is this intentional? 

Should I have to call less.registerStylesheets manually? Or should this always register on load?

**Comment by lukeapage** [comment]
I think you should call it manually or else send a pr that if stylesheets is undefined it calls registerStylesheets - otherwise we end up with someone else wanting an option to stop less regitering stylesheets until after pageLoad (they could call it again, but then its being called twice for no reason).

I'm happy if you put a pr to call registerStylesheets in load
