### ISSUE TITLE
data-uri in browser without fallback

### ISSUE THREAD

**Issue by shkarupa-alex** [less/less.js#2354]
Now data-uri function falls back to url() if you use the function in the browser.

It would be great if if doesn't fall, but generate base64 encoded image

**Comment by lukeapage** [comment]
The main reason it doesn't is support for base64 encoding. 

I've just added a fix to master, so the remaining issues to get this working would be
* add a supportsSync to less-browser/file-manager
* add a less-browser environment overridding the default environment that implements encodeBase64

but..

why do you want this?

If you want your browser css to be the same as in production, compile serverside and use live reload. If its for production, a URL( is better because in the browser it will be asynchronous and not go through an extra transformation.. so I can't see a particularly good reason to do this..

**Comment by shkarupa-alex** [comment]
Some month ago i wrote a plugin for CMS that compiles less to css online.
To be able to make such compilation in any hosting i do this online (in browser) and then post result css to server. 

This ability (compilation on shared hosting without any other software - like ruby for SASS) was the main reason why i prefered LESS.

So in production mode in would be great if data-uri would work as node-version.
