### ISSUE TITLE
absolute path for @import

### ISSUE THREAD

**Issue by DarkPark** [less/less.js#2375]
file `entry.develop.less` with
```less
@import "/home/dp/Projects/web/stb/app/less/develop.less";
```
gives this error:
```
'/home/dp/Projects/web/stb/app/less/develop.less' wasn't found in /home/dp/Projects/web/stb/app/less/entry.develop.less 10:0
```
even though the file is there (non-empty and readable of course)
making the path relative solves the problem

**Comment by lukeapage** [comment]
relative paths are a better idea.. but absolute *should* work.

What OS are you on?

**Comment by lukeapage** [comment]
on windows `path.join(".", "c:\dir\file.less")` stays `"c:\dir\file.less"` but `'/home/dp/Projects/web/stb/app/less/develop.less'` becomes `'home/dp/Projects/web/stb/app/less/develop.less'`

So I wonder if on non-windows systems, node path.join removes the starting slash making it absolute. I'm going to improve the error message for now and then it would be good if you could re-test.

**Comment by DarkPark** [comment]
in general I agree that "relative paths are a better idea"
but I have rather complicated setup and absolute paths are better for me
OS is linux

I've tested and unfortunately the absolute path:
```js
path.join('.', '/home/dp/Projects/web/stb/app/less/develop.less')
```
really becomes relative `home/dp/Projects/web/stb/app/less/develop.less`

**Comment by lukeapage** [comment]
That explains it, i will fix it.

**Comment by DarkPark** [comment]
thanks

**Comment by lc60005457** [comment]
@lukeapage I used `less-middleware` with `less old version`，

the `less-mddleware` give `less` a pathRoot `/home/dp/Projects`，

the absolute path should be `@import "/web/stb/app/less/develop.less"` but not is `@import "/home/dp/Projects/web/stb/app/less/develop.less"`，

because `/home/dp/Projects` should different at different computer

it should be config in `less-middleware` but not in codes.
