### ISSUE TITLE
sourceMap use

### ISSUE THREAD

**Issue by DarkPark** [less/less.js#2376]
It's not clear how to generate source maps.
There is a single paragraph about it in http://lesscss.org/usage/#programmatic-usage.
Without even a simple example it's impossible to make it work easily.
Can you please provide an example?

**Comment by matthew-dean** [comment]
That's a good point. I admit I wouldn't have the first guess how to set those options. Although sourceMapFileInline makes sense. But as far as an external file, not sure. I assume sourceMapUrl is the location of the output file, and not a URL, but I could be wrong.

Since this is more a documentation question, it's best to post that in the issues for https://github.com/less/less-docs. I'll close this here since it's not an issue with Less.js itself.

**Comment by DarkPark** [comment]
thanks
will do
