### ISSUE TITLE
Urdu Translation

### ISSUE THREAD

**Issue by 90skype** [less/less.js#2492]
Hy,
 Hope you are fine. I am Majid the final year student and an active member of amara.org. and i would like to contribute my services in translating the less project into my native language i.e. URDU.
if you give me a chance than i would be very thankful to you and it will help me alot in learning the different ways of subtitling or translation.
thanx.
regards:
Majid Hussain Malik
Email id: 90skype@gmail.com

**Comment by SomMeri** [comment]
Hi, thank you for offer. The easiest way to do translation, is to just fork [documentation repository](https://github.com/less/less-docs/notifications) repository and translate the fork. We would then link your repository [here](http://lesscss.org/about/#translations). 

I will close this issue because it is neither issue nor feature request. If you have further questions about translation, please open issue in [less-docs](https://github.com/less/less-docs/notifications) repo.
