### ISSUE TITLE
use amdclean to reduce the footprint of the browser build

### ISSUE THREAD

**Issue by lukeapage** [less/less.js#2513]

**Comment by lukeapage** [comment]
hrmm the idea is to replace browserify with requirejs, build a bundle, then clean it and end up with a umd wrapped thing with no internal defines and requires. However I am having trouble getting requirejs to generate the bundle.. it seems to suggest it can cope with commonjs, but its just producing rubbish and not including every file. One for a rainy day unless anyone can point me at a guide to exporting commonjs style modules into a require bundle...

**Comment by rjgotten** [comment]
> unless anyone can point me at a guide to exporting commonjs style modules into a require bundle

You rang? ;-)

Have a look at the description for the [cjsTranslate](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L584-L594) option. It mentions specifically that you *must* use relative path module IDs to actual existing files in your `require()` calls and cannot rely on the `node_modules` lookup rules.

As part of those rules; you also cannot rely on a default "index" filename being appended to a `require()` call that points at a directory instead of a file. The Less source currently does rely on that particular mechanism in a few places.

**Comment by lukeapage** [comment]
@rjgotten thanks, that makes sense, I'd read it and thought about modules, but forgotten about index. I might have another go at some point.
