### ISSUE TITLE
Extract doesn't seem to be working when I'm trying to split a string

### ISSUE THREAD

**Issue by corysimmons** [less/less.js#2539]
Given: `@fraction: '1/2';`

How could I get `1`? How could I get `2`?

**Comment by corysimmons** [comment]
I see it's not possible natively, but maybe this should be added? Doesn't seem like it would be too hard of a function.

**Comment by seven-phases-max** [comment]
Less development is mostly use-case-driven, features rarely added just because "it's not hard to add, or just possible to add". I.e. start with https://github.com/less/less.js/blob/master/CONTRIBUTING.md#feature-requests. W/o less or more real-world use-case and a rationale of why exactly this feature woud help there the feature request has very little chances to go to far.

**Comment by corysimmons** [comment]
No problem. I started tinkering around with `extract` and `replace` to help me out but ran into a wall.

```less
.bar {
  @list: '1/4';
  @foo: e(replace(@list, '/', ' '));
  content: extract(@foo, 1);
}
```

returns

```css
.bar {
  content: 1 4;
}
```

Without the `e()` it returns `'1 4'`. Without the `replace()` it returns `'1/4'`.

I'm curious why `extract()` isn't getting `1`... :(

**Comment by seven-phases-max** [comment]
<sup>just in case personally of course I can see what code you're porting: https://github.com/corysimmons/lost/blob/master/stylus/lost.styl#L200 but other don't. Either way, hint: Less is not designed as a sort of scripting language (aka "PHP-like text processor for CSS") so considering how most the code you're porting is written I'd suggest you to give up earlier. Everything written there *is* possible but requires *vastly* different approach and has to be redesigned from scratch. Thus if you expect to achive the goal with a line-by-line translation approach you'll fail for sure)</sup>

**Comment by seven-phases-max** [comment]
Regarding your example. No this is not a use-case example. This is simply abstract snippet you're going to use this thing in. It answers nothing. Well, at quick glance the main questions would be:
Why it is a string? There're no strings in CSS (except `url` and `content` stuff) so why numeric values are encoded with string there? (of course `extract` won't work with "1 2" because it is a single value and not a list).

**Comment by corysimmons** [comment]
I want it to be a string so I can grab the denominator and set it to do some stuff automatically with my grid system (apply a `margin-right: 0` to every `denominator` `nth-child`). It works out really nice with the Stylus and Sass ports.

So far as `extract` not working with `'1 2'`, I thought that `e()` unquoted things (therefore making them not strings in LESS' eyes).

Is there a way to convert the string `'1 2'` into an actual list?

<small>I'm actually really close to getting this port done, this string splitting thing is the last hurdle in my way.</small>

**Comment by seven-phases-max** [comment]
>Is there a way to convert the string  '1 2'  into an actual list?

You always can fall into inline javascript hacks to achieve this. But in normal Less code no, you can't. In Less if you need a number you write it as a number and not as a string (yet, again because unlike Sass and Stylus, Less is not a text-processing scripts execution engine).

---
Here's basic example of why I mentioned that "*vastly* different approach and has to be redesigned from scratch" above.
Just an illustration (I'm not suggesting this as a solution or a sort of), if you compile: 
```less
div {
    @foo: 3~'/'5;
    1: extract(@foo, 1);
    2: extract(@foo, 2);
    3: extract(@foo, 3);
}
```
you get:
```css
div {
  1: 3;
  2: /;
  3: 5;
}
```
See? Obviously ~"/" is not something useful in a real code so for a Less library you'd just need to choose some another symbol (e.g. `3 5`, `3 of 5` etc.). But since the code there was designed for a string-processor one chose to use quotes. And now it's not a surprise you need some dirty hack to port this code to Less.

**Comment by corysimmons** [comment]
Alright thanks for the help.

**Comment by seven-phases-max** [comment]
I marked this as "Feature Request" but since after a few posts it turns into a "How-To" question (that duplicates http://stackoverflow.com/questions/29464046) I'll also mark it for closing...
