### ISSUE TITLE
Escaping problem

### ISSUE THREAD

**Issue by Grawl** [less/less.js#2578]
I trying to use [`postcss-simple-extend`](https://github.com/davidtheclark/postcss-simple-extend) with Less and have no luck with it's custom syntax.

``` less
.link {
    @define-placeholder item-link {};
}
```

Have this error:

```
directive options not recognised
```

Maybe there is a way to output anything into resulting CSS? Like Stylus' [CSS Literal](http://learnboost.github.io/stylus/docs/literal.html) but for strings.

**Comment by rjgotten** [comment]
> @Grawl
> Maybe there is a way to output anything into resulting CSS? 

You have to jump a hoop or two but you can do this quite easily with a [custom `@plugin` function](https://gist.github.com/rjgotten/36427563bda8428fb9d2).

**Comment by seven-phases-max** [comment]
An more easy workaround would be: .link {
    _: ~";@define-placeholder item-link {}";
}

**Comment by rjgotten** [comment]
@seven-phases-max
That renders a junk property though.

**Comment by seven-phases-max** [comment]
@rjgotten Sure hence a "workaround" (though every CSS stylesheet usually has a lot of even formally valid "junk" so nobody cares :)

**Comment by seven-phases-max** [comment]
Speaking of possible fixes, I suppose the parser can recognize an unknown directive of the `@directive optional-something {}` form with just a tiny change (by setting default value of [`hasUnknown`]() to `true`). But this obviously will result in top level directive not nested in `.link` which I suppose is not what intended by above example...

So speaking of ruleset level `literal` feature, what are possible use-cases beside compiling non-CSS sources? Actually if assuming only above example, *just* allowing such literal does not seem to be enough for anything beside empty `{}`... As soon as you have some properties in those `{}` you're not allowed to have it either multiline nor you can use any Less stuff there.

Hmm, the last note leads me to another solution/workaround... Such non-CSS code should be put into a separate CSS and then included with `@import (inline)`.

**Comment by Grawl** [comment]
@seven-phases-max you are thinking with overkills. Actually all PostCSS' guys like me just want to use their postprocessors after generating CSS with preprocessor.

Ideal workaround for me will be something that I don't have to do; but if you ask me what I will approve I will name something like this:

```less
.link {
    escape('@define-placeholder item-link {};');
}
```

But not something crazy in Less style like [your example](https://gist.github.com/rjgotten/36427563bda8428fb9d2):

```less
.link {
  @plugin "literal.js";
  @literal : literal( "@define-placeholder item-link {};" );
  @literal();
}
```

Please.

Defining something like a function just for escaping and calling it after is craziest think I ever seen after Perl.

**Comment by seven-phases-max** [comment]
@Grawl  Yes, I always do... Because those "seems to be easy to add features" almost always tend to end up misused and abused later leading to new problems. The good example is ~"" itself, while initially made to just pass unknown/invalid value through the parser later become used more like string manipulation/concatenation stuff with all of the question like "why `lighten(~"#123", 50%)` does not work and so on. So it's not a strange idea to predict/expect and make it protective from exactly the same things happen for such `escape` too. E.g., why my code like:
```
.link {
    escape('@define-placeholder item-link {
        color: @main-theme-color;
        width: 10px;
    };');
}
```
does not work?

---
The other remark (probably sort of unrelated but to illustrate why the use-case itself is a bit harmful). 

>want to use their postprocessors after generating CSS with preprocessor.

Both are *pre*-processors actually. The fact that such postcss tools do not require their own file extension do no make them *post*. Both Less and the plugin you mentioned compile *non-CSS* code to a CSS code, hense *pre*. The proper example of *post*-processor is Autoprefixer (because it does compile CSS to CSS).
So taking this into account, here's yet another hypothetical workaround: apply your PostCSS *before* Less using same literal escaping for a Less code non-recognized by PostCSS ;)

**Comment by Grawl** [comment]
You are right.

Now I have to call @ai here to let you guys to talk :)

**Comment by Grawl** [comment]
Also, for escaped parts there is a good idea how to add variables into: **interpolation** :)

```less
.link {
    escape('@define-placeholder item-link {
        color: #{main-theme-color};
        width: 10px;
    }');
}
```

**Comment by matthew-dean** [comment]
Interesting. PostCSS has come up a bit lately. I'm wondering if there's a way to create an interoperable CSS AST between different CSS processors (much like the SpiderMonkey AST for JavaScript), so that instead of parsing Less into an AST, then outputting a CSS string, then passing it into a postprocessor like autoprefixer, which again parses into an AST, before transforming, maybe we could directly pass around ASTs, if it was a defined format. That way there's not double parsing on either side.

I mentioned that in this thread as well: postcss/postcss#320

**Comment by rjgotten** [comment]
> @Grawl 
> But not something crazy in Less style

I never claimed it looked pretty, did I? ;-)

For the record; I agree that this is somewhat crazy, but it's due to a limitation that functions have to output a Less value and cannot render output directly. The only structured way to work around that limitation is by encapsulating your custom AST constructions into a detached ruleset and sending that back as the result value of the function. Then when you render the detached ruleset that custom bit of AST gets merged in and things work as you'd expect from there.

> @matthew-dean 
> maybe we could directly pass around ASTs, if it was a defined format. 

If you're going to reach out to other projects for this, I'd suggest also reaching out to Microsoft's Visual Studio team. They'll likely be very interested in having the compiler output an interoperable AST as well.

They need to hook up Visual Studio's Intellisense to provide Less syntax highlighting, speculative warnings/errors and autocompletion. That needs an AST to do its magic as well. Currently they are runnng their own parser, but it's already several language features behind because it's based on version 1.7 of the official compiler.
