### ISSUE TITLE
Detached rulesets in list literals bind inconsistently

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2587]
Source: 

``` less
.mixin1(@scalar, @a) {
  value: @scalar;
}

a {
  .mixin1(a, b c);
}

.mixin2(@scalar, @a @b) {
  value: @scalar;
}

a {
  .mixin2(a, b {color: green; });
}
```

The only difference between the two callsites is that the first passes a list of two keywords, whereas the second passes a list of a keyword and a DR.

These two calls bind their parameters differently; adding `@b` to the first definition or removing it from the second will cause an error.

I have no idea which one is correct (or whether both should work), but the inconsistency is quite annoying.

If it would work with list variables too, list parameter comprehension like the second example would be quite nice.

**Comment by rjgotten** [comment]
### Regarding the first case
As you've already noticed, Less doesn't have list comprehension or destructuring. Rather than complaining about a missing argument separator, the compiler silently turns the mixin declaration `.mixin1(@scalar, @a @b)` into `.mixin1(@scalar, @a, @b)`, which has three parameters.

The call `.mixin1(a, b c)` only passes two arguments: one scalar, followed by one list of two components. The lack of a signature with a suitable argument count then causes the error 'No matching definition was found' to be thrown.

### Regarding the second case
The parser function for arguments does not parse a list argument containing a detached ruleset correctly. At the highest level of the mixin call arguments parser routine a parameter can either be an expression *or* a detached ruleset. Lists fall within the domain of expressions, but the expression parser does not take into account the existence of detached rulesets as a parsable expression member entity.

The result is that the entity parser backs out after having read the first list member and produces a simple (non-list) argument. It then arrives back in the arguments parser, which in turn consumes the remaining white-space and following detached ruleset as a third parameter. (Same as above in the first case; the parser ignores the non-existence of an argument separator symbol.)

The net effect is that it is not the mixin *declaration* but the mixin *call* that is silently turned into a call `.mixin2(a, b, { color: green })` with three arguments at which point a declaration `.mixin(@scalar, @a)` would again have a mismatch in argument count, again leading to the error 'No matching definition was found' being thrown.

------

Whether the silent addition of a missing argument separator symbol is a bug is debatable. Less accepts either comma's or semi-colons to begin with, though officially you should use semi-colons to accomodate comma-separated list values. Treating the space as a separator itself can be seen as the logical conclusion to this behavior.

The fact that the parser misinterprets the argument structure and doesn't understand detached rulesets inside a list is definitely a bug; no excuse for that behavior.

**Comment by seven-phases-max** [comment]
Technically I think a minimized example of the problem is valid:
```less
@dr: {foo: bar}
@compound-value-1: x @dr; // OK
@compound-value-2: x {foo: bar}; // Error
// etc., e.g.:
@eg: {foo: bar} {foo: bar}; // list of two DR values, error
```
And its somewhere between feature-request/bug (it jus wasn't considered during DR implementation, but it is quite inconsistent in a long run).
But let's close it for now anyway (it's barely safe to fix/improve before fixing more fundamental DR/mixin problems discussed at https://github.com/less/less-meta/issues).
