### ISSUE TITLE
Request: CSS Guard - When not

### ISSUE THREAD

**Issue by Ashbo** [less/less.js#2592]
Hi,

I'd like to request that a feature is added where you can use the "not" keyword in a CSS guard. For example, in my job, we use LESS to build our websites. We do a lot of franchise work so each franchise has a variable such as:

```less
@franchise-name: foo;
```

We build websites with 15-20 franchises, sometimes more. I came across this today. I wanted to apply something along the lines of

```less
& when not (@franchise-name = foo) {
    //Button styles
}
//Button styles to apply when @franchise-name = foo
```

However I've had to do a & when statement below the original CSS, meaning there's unnecessary compiling happening.

It's hard to explain it however it's something which will not only come in handy for us as a company, but it will become very useful for a handful of other LESS users.

I'm very keen to see this sort of feature introduced as it would come in very very useful!

**Comment by seven-phases-max** [comment]
I can't understand what you're requwaesting here. As it's already mentioned `not` *is* supported in any guerds (it *does not matter* if it's "CCS" or a mixin guard). So please provide more details on you use-case (because it's absolutely not clear why do you think it's *not* working).

If you don't understand how to use/simplify nested classes/guards ([for example](http://codepen.io/seven-phases-max/pen/dopWar?editors=110)) consider asking your question at SO. Yet, again the issue tracker is not for asking "How-To" question (and yet again I can't see any issue/bug report or feature request in your post).
