### ISSUE TITLE
API for getting variables 

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#2597]
is there a way to get variables that have been defined in a specific `.less` file?

In other words, if I have the following defined in `variables.less`:

``` less
@foo: "bar"
```

Is there a way to get `foo` and its value programmatically?

**Comment by seven-phases-max** [comment]
Something like in the first post of #2231, with a few modifications though:
* it should really be *post* evaluation visitor (i.e. not `isPreVisitor = true;`, obviously for `1 + 2` you want `3` and not the initial expression).
* Instead of kludgy `.value.eval({}).value` it should be `value.toCSS()` or so.

(Sorry, I can't craft a more detailed example right now, but I guess you'll find some hints on proper variable value handling by investingating corresponding sources: good start is https://github.com/less/less.js/blob/master/lib/less/tree/rule.js)

**Comment by mikejr83** [comment]
@seven-phases-max,

I looked through the code for a bit in regards to trying to come up with my own solution of this (and before I submitted #2755). Could you give a bit of guidance on how the code uses the rules (ruleset) to evaluate all the variables.

Psuedo code or a pointer to where the LESS processor actually does this would be helpful. If the values of the variables are evaluated and cached in a single step it would be helpful if you could point this location out.

**Comment by seven-phases-max** [comment]
Well, in short, all Less nodes (i.e. every object in the AST) has `eval` function. However, since the evaluation is context dependend, instead of calling `eval` on your own, the proper method is to use already evaluted tree produced by the compiler itself. Basically the `root` object you'd get in a plugin *is* the evaluated AST (thus its first level `rules` contains evaluated global variables).

**Comment by mikejr83** [comment]
Ok, that makes a bit more sense. Essentially I'm going to need to write a plugin to get a list of these evaluated `rules`. My plugin could take in a a reference to a hash and populate it with the key/value set. Sound about correct?

**Comment by seven-phases-max** [comment]
Yes, something like this (though I can't be sure about certain details as I'm not able to check any particular JS code myself these days).

**Comment by mikejr83** [comment]
Great. That's already the path I'm pursuing with dotless. Hopefully the crossover in how everything works is similar (albeit I'm much more adept at writing C# and hacking JS).

**Comment by Craga89** [comment]
FYI I rolled my own solution to this as a typical less plugin: [less-plugin-variables-output](https://github.com/Craga89/less-plugin-variables-output). Also available on NPM 👍
