### ISSUE TITLE
how to use less in nodejs, the easy way?

### ISSUE THREAD

**Issue by tcdona** [less/less.js#2604]
I need compile multi string content of less text to ./css/*.css , and search lib is ./lesslib/*.less
1 less.Parser has too option，i can't make it work.
2 no grunt, no gulp
3 less.render may be can't import the lib

how can I do that?

**Comment by seven-phases-max** [comment]
Sorry, the issue tracker is [not for](https://github.com/less/less.js#more-information) generic "How-To" Less questions, to find help for Less usage consider using [SO](http://stackoverflow.com/questions/tagged/less) (and when you'll ask there, make sure to include the code you've tried, otherwise it's nearly impossible to guess what you actually need).

**Comment by lukeapage** [comment]
Examples are on the website and in this repo in bin/lessc

**Comment by tcdona** [comment]
cool, thank you very much !
