### ISSUE TITLE
Less.js Truck Factor

### ISSUE THREAD

**Issue by gavelino** [less/less.js#2655]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Less.js** and obtained a value of **1**.

The developer responsible for this TF is:

Luke Page - author of 76% of the files 

To validate our results, we would like to ask **Less.js** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Less.js**?

(b) Do you agree that **Less.js** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Less.js** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by seven-phases-max** [comment]
The high TF is actually a result of recent refactoring and reorganization of the code-base (where most of files were moved/splitted/merged in a way `git` can't resolve properly, so current repository info of files history/authors is not strictly valid).

>(a)

Yes. 

>(a)

Yes. 

>(b)

Yes. Code-base does not have any detailed documentation, but the language itself is documented pretty well, beside there're a few contributors that are more or less familiar with the compiler/language internals.

**Comment by lukeapage** [comment]
> The high TF is actually a result of recent refactoring and reorganization of the code-base (where most of files were moved/splitted/merged in a way git can't resolve quite properly, so current repository info of files history/authors is just not strictly valid).

Yes, I agree on that.

@gavelino the history is interesting because less.js was created by @cloudhead and though still around he decided not to be so involved any more. At that point less.js could have slowly died - it lacked support for some newer css features and without those fixes being merged and releases done, it would cause problems for people.

As @cloudhead believed then, I believe now that less.js doesn't really *need* new features, but instead needs a minimal amount of bug fixing and maintenance. When there is a large enough number of users in an open source project you generally see people picking up bugs and fixing them (in fact sometimes people are put off contributing to a very well maintained codebase because the author fixes the bug so quickley. Case in point being babel.js - I may have contributed if the few bugs I raised there weren't resolved within 24 hours of opening).

So actually I believe that unless some outside influence causes a large feature to be required, they key to reducing TF (or is it increasing?) is simply having people a) responding to issues b) able to merge PR's and do a release. To that end, we have several maintainers with access to the repository that can stop that happening. But while I remember @seven-phases-max are you interested in me giving you permission to the npm repo?

> (a) Do you agree that the listed developer is the main developer of Less.js?

of the last 3 years, excluding the last 4 months, yes.

> (b) Do you agree that Less.js will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

No, probably not.

> (c) Does Less.js have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

yes.
documentation
good code structure
tests
multiple people with access to the repo

**Comment by matthew-dean** [comment]
To that end, is it possible to start adding more inline documentation to functions within the less library? Not necessarily as a big project, but just a goal to have some kind of standard function documentation?

**Comment by seven-phases-max** [comment]
@lukeapage 
>But while I remember @seven-phases-max are you interested in me giving you permission to the npm repo?

To be honest, no, I'm in fear of extra (informal self-induced of course) responsibilities this can put on me :blush: (I think it will be OK when/if this is necessary, but by now I don't see any real need for this).

**Comment by SomMeri** [comment]
> (a)

Yes.

> (b) (c)

Less.js code is well structured I would say, so it is possible to get into it relatively fast. It does not have impenetrable parts where you would need to puzzle out some tricky magic nor anything like that. If Lukeapage leaves, the speed of development would slow down. What I am trying to say is that it is possible for new people to just read the code and understand what is going on assuming they know less itself well enough.

So, it basically boils down to whether there will be someone having time and willingness to fix bugs as they are reported or add smallish features.

**Comment by matthew-dean** [comment]
I'd rather say that @lukeapage is irreplaceable so he doesn't go anywhere, lol.

**Comment by rjgotten** [comment]
> What I am trying to say is that it is possible for new people to just read the code and understand what is going on assuming they know less itself well enough.

That holds true in general, but there are *some* areas of the codebase (i.e. processing mixin calls) that are very, very opaque. (Admittedly; mixin calls were also marked as one of the potential areas for cleanup, streamlining and performance improvement, so it's not like this is a lasting thing...)

**Comment by gavelino** [comment]
Thank you for the comments. We really appreciate the feedback.
