### ISSUE TITLE
Reactivate browser specific css properties

### ISSUE THREAD

**Issue by mau-ferrusca** [less/less.js#2661]
Hi.

Winless just upgraded less.js to 1.6.0 and I've noticed that some vendor-prefixed properties (border radius, box-sizing, etc) are being compiled without the -moz and -webkit properties.

Is there a way to switch them on?

Thanks

**Comment by seven-phases-max** [comment]
I suppose this is something specific to WinLess and its settings (Most likely it uses [Autoprefixer](https://github.com/postcss/autoprefixer) or or sort of, so check WinLess documentation for options you have there).

Less itself does not add or remove any prefixes (or anything at all... Not counting that since v.2.x it also supports Autoprefixer as a plugin).

**Comment by mau-ferrusca** [comment]
Thanks! I will, but there isn't a check box in WinLess to turn on/off prefixes and I get the same results using Prepros. I didn't find any info about the vendor-specific properties being deprecated in the latest less.js, so I'm a bit puzzled.

**Comment by mau-ferrusca** [comment]
Simply compiling this from less:
`.no-box-shadow{
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  box-shadow: none;	       
}`

to css results in:
`.no-box-shadow {
  box-shadow: none;
}`

from both WinLess and Prepros.

**Comment by seven-phases-max** [comment]
>I didn't find any info about the vendor-specific properties being deprecated in the latest less.js

Sure, because (as I already mentioned) Less itself does not modify those (and never will be since it's just out of its scope). Just in case, how do you actually look at your resulting CSS file, by opening in some Editor/IDE or via browser debugging tools?

---
Aside of above notice that Autoprefixer (which is at least included for sure with Prepros) will actually remove `-moz` and `-webkit` properties with default "latest 2 versions" option, because neither prefix is necessary for the most CSS properties in those "latest 2 versions" of the corresponding browsers... So you'll actually will need to turn autoprefixing off or tune it to support older browser versions.

**Comment by mau-ferrusca** [comment]
>Just in case, how do you actually look at your resulting CSS file, by opening in some Editor/IDE or via browser debugging tools?

I open the compiled file locally in an editor. And I turned off Autoprefixing in Prepros. 

Thank you!

**Comment by seven-phases-max** [comment]
I supposed these option(s) (of not present in GUI) are laid somewhere with in files sitting in WinLess directory. But honestly I have no idea where exactly since I don't have it (neither can quickly find in its sources).

---
Either way if you don't mind I'll close this since it's definitelyy not a Less issue.

**Comment by seven-phases-max** [comment]
Closing as not Less issue.
