### ISSUE TITLE
Random iOS Safari compile issues

### ISSUE THREAD

**Issue by knyttl** [less/less.js#2668]
I am having the same iOS/Safari issue on http://overtone.cz. The strange thing is that on some iOS devices it works correctly, on some others I am getting random compilation errors even though all the devices have the same iOS/Safari versions.

Using: Leaner CSS v2.5.1

I am including screenshots to demonstrate the random behaviour when reloading the site.

![img_0070](https://cloud.githubusercontent.com/assets/401107/9269667/1ec41dba-426c-11e5-912f-d7caa8a13f7d.PNG)

![img_0071](https://cloud.githubusercontent.com/assets/401107/9269672/287b8b68-426c-11e5-83f0-8c285d935d35.PNG)

![img_0072](https://cloud.githubusercontent.com/assets/401107/9269675/2d38fc80-426c-11e5-8baa-7bd84f0e46b6.PNG)

**Comment by rjgotten** [comment]
> The strange thing is that on some iOS devices it works correctly, on some others I am getting random compilation errors even though all the devices have the same iOS/Safari versions.

iOS 8.x has a very annoying bug in the optimizing compiler of Safari's JS engine. It creates a bogus length property on plain JS objects that contain purely numerical property names: https://bugs.webkit.org/show_bug.cgi?id=142792

This bug will apparantly only trigger on ARM64 hardware; it won't trigger on ARM32 hardware and it won't trigger on x86/x64 hardware. (That last bit means it will never trigger on the simulator bundled with XCode.)

Because it involves the optimizing compiler, it will also *only* trigger if a certain segment of code is called enough times with a stable type signature for the runtime to consider it being worth to optimize. But even at that point the runtme may still take into account availability checks such as current CPU load or other factors and even if it doesn't; general CPU load my influence how long the optimizing compilation takes to complete and at which point the optimized code 'goes live'. This leaves the actual moment at which the bug will surface unpredictible making this a thoroughly non-deterministic bug to reproduce.

This is not something any JavaScript library can solve, because it's not their bug to solve. Only Apple can solve this problem and sofar they have shown no signs of deigning it worthy of being backported to current iOS versions. (It will probably go into iOS 9, leaving iOS 8 gimped.)

In the meantime, the only thing libraries can do is to harden the 'is it an array-like?' checks they implement to attempt to avoid the issue. Both jQuery and Underscore have infact done so already: the deceptively easy hardening fix is to not simply check for `object.length` but to check for `"length" in object && object.length` instead.

(And to think; all of this caused by a mix-up between a greater than operator with a right shift operator on Apple's part. No, I'm not kidding here: http://trac.webkit.org/changeset/182058)

**Comment by knyttl** [comment]
Thanks for explanation – however, is there any kind of workaround/hack to overcome this issue?

**Comment by rjgotten** [comment]
The only workaround is to comb through all the libraries you use and all your own code, looking up all places where a `length` property is used and in those places include the hardening fix based on the `in` operator that I wrote about.

In case of Less specifically, I'd just compile it to CSS server-side as part of a build step and then serve the precompiled CSS.

**Comment by matthew-dean** [comment]
@rjgotten Are you saying that the Less lib does checks for "array-ness" based on checking a length property?

**Comment by rjgotten** [comment]
> Are you saying that the Less lib does checks for "array-ness" based on checking a length property?

As you've already discovered: yes.
And it doesn't have to be Less itself. It can also be one of its dependencies.

**Comment by naluhh** [comment]
The issue seems to be still here on iOS 9.1. Works fine on simulator, but takes minutes to compile on real devices. Happened on every device I could test : iPhone 6S plus, iPad air 2, iPad pro, iPhone 5.
