### ISSUE TITLE
error evaluating function `color`

### ISSUE THREAD

**Issue by kamitori** [less/less.js#2692]
This is my code
````
.random_color(){
		@random_value: `Math.floor(Math.random()*16777215).toString(16)`;
		@color_hex: e(@random_value);
		@color: color("#@{color_hex}");
	}
body{
        .random_color();
	background-color: @color;
}
````

When i run, sometime it's error:
"error evaluating function `color`: argument must be a color keyword or 3/6 digit hex e.g. #FFF"

**Comment by SomMeri** [comment]
The problem is in your random color generation `Math.floor(Math.random()*16777215).toString(16)` It does not generate valid colors if random returns very small number. For example. if random returns 0, your color becomes `#0` [see example here](http://less2css.org/#%7B%22less%22%3A%22.random_color()%7B%5Cn%20%20%40random_value%3A%20%60Math.floor(0*16777215).toString(16)%60%3B%5Cn%20%20%40color_hex%3A%20e(%40random_value)%3B%5Cn%2F%2F%20%20%40color%3A%20color(%5C%22%23%40%7Bcolor_hex%7D%5C%22)%3B%5Cn%7D%5Cnbody%7B%5Cn%20%20.random_color()%3B%5Cn%20%20string%3A%20%5C%22%23%40%7Bcolor_hex%7D%5C%22%3B%5Cn%2F%2F%20%20background-color%3A%20%40color%3B%5Cn%7D%22%7D)

Off-topic: Please use [github code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for code. The code will be easier to read and github will not send emails to whoever has the same username as your variables. I added code block into your original submission, so the issue is easier to read (and you can see how it is supposed to look like).
