### ISSUE TITLE
Add ability to export a CSS AST (instead of a CSS string) for post-processing

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#2707]
_(use postcss)_ It's very fast and has many plugins that Less could easily be integrated without re-parsing.

**Comment by matthew-dean** [comment]
There was some discussion with the PostCSS team about possibly sending an AST from Less to the PostCSS processor for things like Autoprefixer (instead of a string that gets re-parsed). So I think it's possible a PR for that could go in. It's probably a chunk of work though that someone would have to take on. And I'm not sure how high a priority it is.

**Comment by stevenvachon** [comment]
Interesting. Though, I was more suggesting that Less be written as a PostCSS plugin.

**Comment by matthew-dean** [comment]
@stevenvachon I think you could possibly do that with Sass, but I doubt it's possible with Less, since Less has block scoping and, to my knowledge, PostCSS and Sass don't. If I understand PostCSS correctly, PostCSS is a set of transformation rules. But in Less, those transformation rules are not static, nor are they necessary global. They're dependent on scope. 

Less also supports JavaScript plugins that are block-scoped, and PostCSS has no such concept. Anything you add to the "processing stack" is effectively global. An expert in PostCSS could correct me, but I believe the sophistication of the Less parser / interpreter (or maybe just interpreter and not so much parser) is beyond PostCSS's capabilities. 

However, once Less forms a CSS document, then, for sure, that can transform in PostCSS like any regular CSS. Other than that, probably not going to happen.

**Comment by stevenvachon** [comment]
Thanks!

@ai comments?

**Comment by ai** [comment]
We have file-scoping plugins by postcss-use and block-scoping by postcss-plugin-context.

So PostCSS core just gives you AST and you can add any scoping that you want.

CSS Modules is good example.

**Comment by seven-phases-max** [comment]
The common mistake is thinking that the bottleneck is the parser, thus believing that a hypothetic postcss-based compiler remains as fast as "empty" postcss pass-through benchmark even after you'll put all Less features in.

**Comment by stevenvachon** [comment]
I don't think of less.js as slow and needs to be made faster. I just think that postcss is a great architecture, less is a great language and having the two work together without a second parse would be great design.

**Comment by matthew-dean** [comment]
> having the two work together without a second parse would be great design.

I would support that as well, for different reasons. I would like to be able to work more easily directly with the AST, to do things like partial parsing, and as you say, passing an object to other libs or a JS environment instead of a string. Of course, that may already be possible but not documented.

**Comment by rjgotten** [comment]
I wonder how easy it would be to factor out the current `toCSS` call on Less's tree nodes into a post-processor that is standard present and enabled.

Then you could wire an AST directly into other tools by lobbing off the post processor and receiving back the full transformed CSS AST instead of the flat string.

**Comment by zephraph** [comment]
I'm coming at this from a bit of a different perspective. The linting ecosystem for less is really lacking. Being able to export an AST to PostCSS would make it easy to hook into something like [stylelint](https://github.com/stylelint/styelint) to build a better linting utility without having to write a whole new parser.

**Comment by matthew-dean** [comment]
@zephraph Yeah, I'd like to export a _Less_ AST (that is, an evaluated but not flattened tree) before it's converted to a _CSS_ AST, but I'm not sure how feasible that is. But a CSS object seems possible, and since a CSS AST structure is arbitrary, it makes sense to use PostCSS's AST structure (although I'm not sure where that's documented). Probably the first step would be to change all the toCSS() methods to build an object, and the very last step if CSS is your target is essentially to convert the object to a string.

**Comment by zephraph** [comment]
That's exactly what I was thinking. Converting it to a CSS AST would be pointless as postcss could just build that out on it's own. According to the README you can [add a custom stynax](https://github.com/postcss/postcss#custom-syntaxes) by providing a parse method (see [this example](https://github.com/postcss/postcss-scss/blob/master/lib/scss-parse.es6)). The trick is that that method is expected to return a [root](https://github.com/postcss/postcss/blob/master/lib/root.es6) object from postcss. Essentially that means entirely converting the less syntax tree to be made up of postcss nodes.

**Comment by matthew-dean** [comment]
> Converting it to a CSS AST would be pointless as postcss could just build that out on it's own. 

Having spent some time in the Less code-base, I'd be skeptical of that statement, but ok.

Probably the easiest path from A to B would be to
a) create a plugin hook in Less's plugin API, that allows you to
b) receive the Less AST and output something else, so that
c) you can add a Less plugin that outputs a PostCSS AST.

Less also allows pre-processing plugins, so it may be possible to add a Less plugin to pass in a PostCSS AST and bypass the Less parser, but I'm not sure why that would be desirable. But it's probably possible, which would would allow you to add a Less plugin to make it, effectively, a PostCSS plugin. To my knowledge, step A is probably quite a bit of rewriting though. Not sure.

**Comment by zephraph** [comment]
By what I said above, I simply meant that Less could output the css and then postcss could build it's own AST from that (as per usual). I've been investigating the plugin route on my own. It's certainly not an easy prospect, but then I guess not much of this will be easy. I'll continue to investigate though, because this is a feature that would be greatly beneficial to me.

**Comment by matthew-dean** [comment]
> By what I said above, I simply meant that Less could output the css and then postcss could build it's own AST from that 

Oh right, that's what already exists. Isn't that what we're trying to solve?

**Comment by ai** [comment]
Awesome task :). BTW, few people ask me about Less parser (to PostCSS AST) because they want to use Stylelint linter for Less sources.

Converting Less AST to PostCSS AST is a best way for my opinion, because it is very fast. Stringifing from Less to CSS and then reparse it in PostCSS will be few times slower.

**Comment by ai** [comment]
But, if you want the faster way to solve this issue, you can just extend current PostCSS parser to support Less sources (as I understand Less is very close to Sass).

For example, in [postcss-scss](https://github.com/postcss/postcss-scss) I just copy-paste a tokenizer, add few lines to it and extend `Parser` class. It took only about a day.

**Comment by matthew-dean** [comment]
@ai Oh, I get what you were saying. Sorry, you just meant that the parsing would be similar between SCSS and Less? To some degree, yes.

**Comment by matthew-dean** [comment]
So, I went away for the past few months and tinkered with this and finally have this: https://github.com/Crunch/postcss-less

So, per @ai's suggestion, this postcss plugin converts the Less AST to a PostCSS AST directly. I wanted to basically do a proof-of-concept to demonstrate that you could essentially use Less function calls to receive the Less AST without the feature needing to be added to the Less side. Getting access to the AST wasn't too hard, as it basically only required calling Less's `parse()` function, evaluating the tree, and then calling the render method.

But... in order to convert ASTs, I pretty much had to hack the balls out of the Less AST. And it pretty well convinced me that adding any AST feature for Less plugins was pretty much pointless. The Less AST is not for mere mortals. There are no convenience methods for walking the nodes, or accessing parents, or even converting a single Node to its resulting CSS, even if evaluated. It just wasn't built to be consumed in an external API, so no "consumer-facing" methods really exist. It's built to be parsed from a string, and then evaluate to a string, and in between the objects created are pretty opaque.

But: as far as the original issue:

> I was more suggesting that Less be written as a PostCSS plugin

After a lot of work, that is now done. So this can be closed, I think.

**Comment by matthew-dean** [comment]
Closing as there is a third-party solution.
