### ISSUE TITLE
Mixed backgrounds suggestion

### ISSUE THREAD

**Issue by ghost** [less/less.js#2744]
Hello. I have interest idea with CSS3 backgrounds. I thinking about mix classes for few background variants. 

```
.one {
  background-image: url(one.png), none;
}

.two {
  background-image: none, url(two.png);
}

.one.two {
  background-image: url(one.png), url(two.png);
}
```

Also I thinking about interpolation of animation. I mean create frames. frame0, frame1....frameN. It also uses cross-class backgrounds principle. And can be used with transition and javascript.

**Comment by seven-phases-max** [comment]
Sorry, but it's a bit unclear what exactly you're proposing. Could you please provide more details?
(typical use-case, example Less code -> corresponding CSS result etc.).

**Comment by acterhd** [comment]
I propose mix two or more  classes (styles) for make  new class (new style).

**Comment by seven-phases-max** [comment]
Please provide some concrete example (or a few) of hypotetical syntax of the feature you're proposing (yet again Less code + CSS result). I'm afraid your textual description is too broad and too blurrish to understand.
A typical feature-purpose looks like:
1. I need to generate *this* CSS (code follows).
2. I want this CSS to be generated with such Less code (code follows).

**Comment by acterhd** [comment]
I sended to email in Russian. Hard syntax.

**Comment by acterhd** [comment]
```
@name1 = .one;
@name2 = .two;
#{@name1} {
  background-image: from(another)?none, url(one.png);
}

#{@name2} {
  background-image: url(two.png), from(another)?none;
}

function mix(@name1, @name2){
  #{@name1+@name2} {
    selectorBy(@name1) + selectorBy(@name2)
  }
}
```

**Comment by seven-phases-max** [comment]
Ok, so how it would be different from already possible:
```less
.one {
    background-image+: url(one.png);
}

.two {
    background-image+: url(two.png);
}

.one.two {
  .one;
  .two;
}
```

**Comment by acterhd** [comment]
By layer level. My feature define layer level of backgrounds.

**Comment by seven-phases-max** [comment]
I'm afraid it's still too abstract. "Layer level"? You mean those `?none` things? And what is their benefit over my example above? 

OK, so let it be, but I hope you realize that just throwing some `fnord` keywords in with a magic behaviour w/o taking other language features (and current compiler workflow) into account pretty much guarantees that the feature of interest is not going to be ever implemented (just because nobody understands what exactly it is for and why to write more compiler code just to get something already possible. Unless you put some efforts to make others to share your belief of it being "more flexible"). Unless you're going to implement it yourself, are you?

>Also I suggest add CSS3 blending support. 

Sorry, but this is not how the tracker works. Each new feature request/proposal needs its own ticket (topic) because each one need a separate discussion and decision (it's not like a board for "here's list of my wishes" posts).

**Comment by acterhd** [comment]
It means, that if no adding, then will none, if some another with plus
operator, then will another value.
Also I think priority. If have sign "?" then will less priority. If have no
"?" sign, then will have high priority.
?url(one.png) + ?url(another.png) will give right operand property.

2015-12-03 22:31 GMT+08:00 Max Mikhailov <notifications@github.com>:

**Comment by acterhd** [comment]
I think found solution. 
Need custom properties support, so need  browser custom properties in Less. 

`@name: 10px;` Less declaration 

`--name: 10px;` Browser declaration 

`--name: @name;` No comments

**Comment by matthew-dean** [comment]
Huh?
