### ISSUE TITLE
Using extend inside a ruleset argument for a mixin

### ISSUE THREAD

**Issue by wjohnsto** [less/less.js#2748]
I'm using LESS v2.5.3.

I am trying to extend an element rule inside a ruleset in a mixin as follows:

```
h1 {
    font-size: 3em;
}

.hero {
    & > .hero-title {
        font-size: 1.5em;

        .phablet({
            &:extend(h1);
        });
    }
}
```

The `.phablet` mixin is a mixin that does a min-width media query for phablets. Based on my limited knowledge from reading #1048 it seems like this should work (the font-size should be set to 3em on `.phablets`. The less compiles fine, but nothing is output, so the font-size remains at 1.5em. Am I doing something wrong?

EDIT: Note this is a somewhat contrived example. In my own code `h1s` have a bunch of media queries associated with them, and what I would like to do is use the `.phablet` mixin to reset `.hero-title` to use those media queries.

**Comment by SomMeri** [comment]
The `:extend` inside `@media` directive is scoped only to rulesets written inside that directive. E.g. this:
```` less
h1 { font-size: 3em; }
@media print {
    div-phablet {
      &:extend(h1);
    }
}
````

compiles into ([live example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22h1%20%7B%5Cn%20%20%20%20font-size%3A%203em%3B%5Cn%7D%5Cn%5Cn%40media%20print%20%7B%5Cn%20%20%20%20div-phablet%20%7B%5Cn%20%20%20%20%20%20%26%3Aextend(h1)%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%22%7D)):
````
h1 {
  font-size: 3em;
}
````

Example without media:
````less
h1 {  font-size: 3em; }
div-phablet {
  &:extend(h1);
}
````

compiles into ([live example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22h1%20%7B%5Cn%20%20%20%20font-size%3A%203em%3B%5Cn%7D%5Cn%5Cndiv-phablet%20%7B%5Cn%20%20%26%3Aextend(h1)%3B%5Cn%7D%5Cn%22%7D))
````css
h1, div-phablet {
  font-size: 3em;
}
````

If your `.phablet` mixin looks somewhat [like this](http://lesscss.org/less-preview/#%7B%22less%22%3A%22h1%20%7B%5Cn%20%20%20%20font-size%3A%203em%3B%5Cn%7D%5Cn%5Cn.phablet(%40detached)%20%7B%5Cn%20%20%40media%20print%20%7B%5Cn%20%20%20%20div-phablet%20%7B%5Cn%20%20%20%20%20%20%40detached()%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.hero%20%7B%5Cn%20%20%20%20%26%20%3E%20.hero-title%20%7B%5Cn%20%20%20%20%20%20%20%20font-size%3A%201.5em%3B%5Cn%5Cn%20%20%20%20%20%20%20%20.phablet(%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%26%3Aextend(h1)%3B%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%7D), then the extend does not hit `h1` because extend is located inside the `@media` directive. When I comment `@media` away, [extend works](http://lesscss.org/less-preview/#%7B%22less%22%3A%22h1%20%7B%5Cn%20%20%20%20font-size%3A%203em%3B%5Cn%7D%5Cn%5Cn.phablet(%40detached)%20%7B%5Cn%2F%2F%20%20%40media%20print%20%7B%5Cn%20%20%20%20div-phablet%20%7B%5Cn%20%20%20%20%20%20%40detached()%3B%5Cn%20%20%20%20%7D%5Cn%2F%2F%20%20%7D%5Cn%7D%5Cn%5Cn.hero%20%7B%5Cn%20%20%20%20%26%20%3E%20.hero-title%20%7B%5Cn%20%20%20%20%20%20%20%20font-size%3A%201.5em%3B%5Cn%5Cn%20%20%20%20%20%20%20%20.phablet(%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%26%3Aextend(h1)%3B%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%7D). I remember this being discussed in some other issue, but I am not sure which one nor how the discussion ended up (e.g. whether it is bug or feature).

**Comment by seven-phases-max** [comment]
It's either #2486 (for the "no error" stuff) or #2095 (for "can it be improved").

**Comment by woble** [comment]
This does not look like a valid syntax to me to begin with.

```less
.phablet({
    &:extend(h1);
});
```

**Comment by SomMeri** [comment]
@woble He defined [detached ruleset](http://lesscss.org/features/#detached-rulesets-feature) in a mixin parameter. It works and is just shorter equivalent for:
````
@detached: {
    &:extend(h1);
};
.phablet(@detached);
````

**Comment by wjohnsto** [comment]
@SomMeri This is unfortunate news :(. Luckily there are other ways to accomplish what I need.
