### ISSUE TITLE
Defining a mixin if not already defined (default mixin)

### ISSUE THREAD

**Issue by Giwayume** [less/less.js#2771]
I'm looking to add overridable mixins in my less library, however I don't see a way to do this since they're not lazy loaded like variables are.

For example
```
.overrides () {
  // stuff
}
@import "library.less"
```

**Comment by seven-phases-max** [comment]
Use [`default()`](http://lesscss.org/functions/#misc-functions-default), e.g.:
```less
.overrides() when (default()) {
    // stuff
}
```
<sub>(this actually has very few to do with "lazy-loading" (mixins are "lazy-loaded" too in fact) - variables are overridable because the *are overridable* (like CSS properies are) and mixins are cascaded as CSS rulesets are (just because a mixin is just a form of a ruleset)).</sub>

Also note that [a ruleset can be assigned to a variable](http://lesscss.org/features/#detached-rulesets-feature) as its value (thus turns into an overridable entity) - for now this is limited to non-parametric rulesets though.

**Comment by seven-phases-max** [comment]
Closing as already existing feature.

**Comment by Giwayume** [comment]
I don't want to keep opening issues for what may be dumb questions, but it seems when using variables with imports it takes the first variable it gets and ignores the override.

main.less
```
@import "imported.less";
@myPath "desired/path";
```
imported.less
```
@myPath "default/path";
@import "@{myPath}";
```

In this example, the second import ends up being "default/path". But If I take out the `@myPath` declaration from `imported.less` it imports "desired/path" instead.

**Comment by seven-phases-max** [comment]
See ["Lazy-Loading"]() (aka "Lazy-Evaluation").
Or better a few tutorials that expose those typical pitfalls in more beginner's friendly way:
* [Variable semantics](http://earthli.com/news/view_article.php?id=2965)
* [... Most Misunderstood ...](http://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/)
For further "Less Usage" questions please use [SO](http://stackoverflow.com/questions/tagged/less).

**Comment by seven-phases-max** [comment]
Make sure you're using a recent version of Less (notice a warning at [Variables in Import Statements](http://lesscss.org/features/#variables-feature-import-statements)).

**Comment by Giwayume** [comment]
I'm using 2.5.1, opened a new issue with a simplified example of my problem #2772.
