### ISSUE TITLE
Question: do we have maps/objects to work with?

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#2795]
Trying to group my grid declarations together. Do we have string key-based objects in Less.js CSS?

In js:
```js
object = { key:value };
```

In CSS?:
```css
@varname {
  key: value
}
```

If so, is there documentation on how to work with them (loops,etc) ?

**Comment by seven-phases-max** [comment]
For a "use right now" thing see [less-plugin-lists:at](). <sub>I was thinking of adding there a support for a rulesets too, but since personally I don't find ruleset-like syntax for maps to have any benefits in this ("plugin-lists") case, I postponed this for next (or so) version.</sub>

For a native syntax/feature proposal see #1848 (and folowing https://github.com/less/less-meta/issues/12).

**Comment by seven-phases-max** [comment]
Merging to #1848.
