### ISSUE TITLE
Back ticks inside quoted strings are treated as JS evaluation block with no means to escape

### ISSUE THREAD

**Issue by rjgotten** [less/less.js#2836]
Apparantly, there is explicit support to inline JS expressions directly into strings (eww!) as per:

```
.rule {
  prop : "3 = `1+2`";
}
```

However, there is no method supplied to insert a **literal** back-tick into a quoted string via escaping.
Infact, it pretty much seems that the replacement logic in `Quoted.prototype.eval` doesn't support **any** kind of escaping, which is frankly; kind of stupid.

Any way to fix that?

**Comment by matthew-dean** [comment]
Bizarrely, the Quoted string inherits from the JsEvalNode node type. Who actually wants this behavior? o_O

**Comment by seven-phases-max** [comment]
Yes, that's weird. I'm pretty sure this was just a misprint :) (though we still probably need to search through old threads just in case if there was some specific intention behind).

**Comment by matthew-dean** [comment]
Well, inheriting from JsEvalNode is pretty explicit. So my guess is someone requested that feature at some point, but that's probably in the early, early days of Less. Probably the inheritance is just so that it was easier to do JS eval within a quote. But with where Less is at now, and with are general discouragement of inline JS, plus the fact that I'm not aware of ever seeing inline JS in a quote like this.... I think it could probably come out at some point.

@rjgotten What was your use case that you were trying to achieve? You give the example for what you can do, but not for you wanted to do but couldn't.

**Comment by rjgotten** [comment]
@matthew-dean 
> What was your use case that you were trying to achieve? You give the example for what you can do, but not for you wanted to do but couldn't.

I created an `assert( message )` plugin method to make the Less compiler conditionally throw an error when certain mixins are called in the wrong way. The format for built-in error messages uses backticks as part of the error message to mark the origin of an error, e.g., the mixin name. I wanted to replicate that format to provide a uniform well-integrated solution.
