### ISSUE TITLE
Identifiers with "named-color" parts are broken.

### ISSUE THREAD

**Issue by ernscht** [less/less.js#2841]
since release 2.6.1 less.js changes the `animation-name` value if it starts with a css color name

    animation: blue-change 5s infinite;
    animation-name: green-black;

results in

    animation: blue change 5s infinite;
    animation-name: #008000;

**Comment by matthew-dean** [comment]
This is due to the change in https://github.com/less/less.js/pull/2806/commits/01b11a7440d6468610a97b57e91486333b993cb5?diff=unified where the regex for named colors was altered.

Technically this should be caught by the parser as a keyword before it attempts any operations. However, I've reverted the regex change which passes all tests, including new ones which test for this case.

**Comment by seven-phases-max** [comment]
Closing as fixed in https://github.com/less/less.js/commit/d07a9b6cc6307318f691ddb682bb9798918e0cc1.
