### ISSUE TITLE
Background size and position calculates into value when "/" is present

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [less/less.js#2872]
[Example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%2F%2F%20Is%20this%20a%20bug%3F%5Cn%2F%2F%20%5C%22%2F%5C%22%20seems%20to%20making%20do%20this.%5Cn%5Cna%20%7B%20%5Cn%20%20background%3A%20url(http%3A%2F%2Fwww.stackoverflow.com%2Ffavicon.ico)%2096%25%2F15%25%20no-repeat%20%23eee%3B%5Cn%7D%5Cn%5Cn%2F%2F%20Works%20fine%20for%20the%20font%20property%5Cn%5Cnb%20%7B%5Cn%20%20font%3A%2096%25%2F15%25%3B%5Cn%7D%22%7D)

Whenever the "/" is present in the background property it divides the two numbers  into a new value, which is rather annoying.

(I checked this issue, and I don't believe it's a duplicate)

**Comment by seven-phases-max** [comment]
It is [expected behaviour](http://lesscss.org/usage/#command-line-usage-strict-math). In your example it's actually `font` property with its value being an especially hardcoded [exception](https://github.com/less/less.js/issues/1627). See also 
examples of escaping syntax (for the default `--strict-math=off`) [there](http://stackoverflow.com/a/33223373/2712740).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.

**Comment by Blue-EyesWhiteDragon** [comment]
Ah right, I feel stupid now.

Anyways thanks for the info!

**Comment by seven-phases-max** [comment]
Not that stupid. It's most likely the inconsistent `font` behaviour that confused you (indeed, how we are supposed to assume what is the right behaviour if *an identical code* produce different results? :P).
