### ISSUE TITLE
Split compiler into library for programatic usage

### ISSUE THREAD

**Issue by itslenny** [less/less.js#2895]
I'm using the less compiler as a component of an application and I noticed it has a fairly large chain of dependencies that really aren't needed for my use case. I'm not using it as a command line tool. I just want to be able to use it programmatically without all the overhead.

Would it be possible to pull the compiler itself into a separate module that the main module could reference?

**Comment by seven-phases-max** [comment]
But the main module is the compiler module (command line tool actually does any significant additional dependencies) . It's just the repo itself that has all platform-specific stuff collected. But I doubt we're going to do the split anytime soon just because of the lack of human resources. Feel free to create a repo/npm-package just with naked `node` stuff only.
