### ISSUE TITLE
Travis builds fail sometimes because of PhantomJS

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2898]
Putting this issue here for tracking.

Travis I think still has an outstanding issue where it's not able to install / run PhantomJS sometimes. (Maybe just for a certain Node version?) So you get PR fails when the code is fine, so it's been unfortunately unreliable lately, which is not great for checking compatibility of new code. I tried to tweak settings to get it to work, but it's not my area of expertise.

**Comment by abrobston** [comment]
See #2905.  The last CI build passed on Appveyor and on all but one Travis instance.  The one that didn't pass was due to a transient connection error, it appears.

**Comment by bd82** [comment]
I believe Travis's connection to the phantomjs mirror is getting throttled.
I've copied a workaround that uses Travis caching to avoid 99% of the downloads.
And also changed the download location back to the original bit bucket.

You can see it in https://github.com/less/less.js/pull/2941

The appveyor build still fails on node.js 0.10 and 0.12.
This is due to a separate issue with a race condition between the downloading of the dependencies from npm and the execution of the **install script** for phantomjs-prebuilt.
I managed to bypass it on Travis using a **retry** hack.
However, in appveyor the retry command does not seem to work...

I don't know how to solve the appveyor problem.
perhaps it is time to consider removing appveyor testing on node.js 0.10 and 0.12.
As those node versions only have two or four months respectability in the node.js Long Term support plan anyhow...

Some claim this problem appears and disappears randomly. Which make sense as it is a race condition... perhaps it will suddenly start working :) 

The root problem is still unresolved here.
That is the dependency on external binaries which do not have sufficiently good hosting.

Perhaps the real solution would be to get rid of phantomjs usage all together.
But this will require a much greater change. 
Because the plugin used for testing **grunt-contrib-jasmine** has absolutely no concept of **separation of concerns** unlike something like [Karma](https://github.com/karma-runner/karma)
which allows usages of different browsers (including phantomjs) different testing libraries (mocha/jasmine/qunit) and different test reporters.

**Comment by bd82** [comment]
I've managed to fix the race condition issue with running phantomjs-prebuilt's own install script
on appveyor as well.

#2941 now passes. 

Please review and merge. 

Keep in mind this does not fix all the build problems. 
but should mitigate 99% of them (after one build succeeds on the default branch 
and the phantomjs binaries will be successfully cached for future builds.
