### ISSUE TITLE
Less function (darken) compiler issue in nodejs

### ISSUE THREAD

**Issue by DanishAzizP** [less/less.js#2913]
![less error](https://cloud.githubusercontent.com/assets/20082762/16256575/8ea0b502-386c-11e6-8904-67c16824fae6.png)
we are passing inline variables through nodejs command line for compiling less but we are facing problem as mention in image.

**Comment by seven-phases-max** [comment]
I can't test this for sure but I suspect `--modify-var=Accent='#bb6407'` is not quite correct CLI syntax. AFAIand[thedocs](lesscss.org/usage/#command-line-usage-modify-variable)R, the proper one would be `--modify-var='Accent=#bb6407'` (also, hmm, double quotes are probably preferred since single quotes may be ambiguous in some systems (Unix-like?)?).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
