### ISSUE TITLE
duplicate mixins definition cause duplication in css

### ISSUE THREAD

**Issue by tanapoln** [less/less.js#2924]
I found a bug in other library that cause duplication of mixins but the behaviour of less compiler also acting wired.

Here `.less` files
```
.border() {
  &:after {
    border: 1px solid grey;
  }
}
.border() {
  &:after {
    border: 1px solid grey;
  }
}
.font-red() {
  color: red;
}
.font-red() {
  color: red;
}

.body {
  .border();
  .font-red();
}
```

It generate this `.css` file
```
.body {
  color: red;
}
.body:after {
  border: 1px solid grey;
}
.body:after {
  border: 1px solid grey;
}
```

As you can see, `.font-red()` mixins is automatically de-duplicate but not for `.border()`.
Is that consider to be a bug?

**Comment by matthew-dean** [comment]
It's not really a bug, but I could see how you might perceive it that way. Even though those examples look similar, you have to consider that each `&:after {}` is a separate ruleset with a separate scope / definition. So each ruleset is evaluated separately. For `font-red()`, those collapse into a single scope, and _that_ ruleset is evaluated once. 

So, Less collapses duplicated properties within rulesets, but doesn't de-duplicate multiple rulesets with the same selectors.

Closing as expected behavior.
