### ISSUE TITLE
Private imports

### ISSUE THREAD

**Issue by alexndreazevedo** [less/less.js#2936]
I propose to create private imports, for internal usage only. It's good to work with frameworks like Bootstrap together with methodologies like BEM. The classes of Bootstrap are very generic, instead BEM classes, that are self described.

What to do when you have some imported classes that you want to reuse them extending other classes, but wont output them?

**Example:**
```less
@import 'bootstrap.less';

// BEM class
.my-bem-block {
    .table; // extend this class with .table from Bootstrap
}
```

**Output:**
```less
// Bootstrap class
.table {
    // rules of .table
}

// BEM class
.my-bem-block {
    // rules of .table
}
```

**Proposal**:
```less
@import (private) 'bootstrap.less';

// BEM class
.my-bem-block {
    .table; // extend this class with .table from Bootstrap
}
```

**Expected output**:
```less
// BEM class
.my-bem-block {
    // rules of .table
}
```

Also, some Boostrap declarations are useful even working with BEM. In this case, I haven't such approach, but something like this should be helpful:

**Proposal**:
```less
// described classes to be outputted
// everything else is imported as private
@import (private) 'bootstrap.less' except {
    .alert
};

// BEM class
.my-bem-block {
   .table; // extend this class with .table from Bootstrap
}
```

**Expected output**:
```less
// Bootstrap class declared to be outputted 
. alert { ... }

// BEM class
.my-bem-block {
    // rules of .table
}
```

Let's discuss about that. This solution could improve the usage of thousands of styles from packages over the methodology chosen by developer.

**Comment by matthew-dean** [comment]
How is this different from `@import (reference)`? I see the pattern is somewhat different, but I'm not sure why it's needed.

Also.... there are a number of features that ended up getting added into Less (or features that were tweaked) because of the way that Bootstrap was designed. In other words, some inflexibilities of Bootstrap were addressed with Less.js workarounds, even though these inflexibilities were by design.

Considering that Bootstrap is no longer targeting Less from v4 on, I'm not sure that Less.js should continue to adopt features as workarounds to Bootstrap's design strategy. Others may have different thoughts though.

**Comment by alexndreazevedo** [comment]
I mentioned Bootstrap as example. It's applied to any other framework. Some npm/bower packages come with less styles, and we can import them for reuse as this way, declaring the exceptions.

**Comment by matthew-dean** [comment]
@alexndreazevedo How is it different from `reference`?
