### ISSUE TITLE
feat: Add support for fallback includes like CSS `font-family`

### ISSUE THREAD

**Issue by diosney** [less/less.js#2957]
Hi, It could be nice if we could do something like this (with any variation, I care about the feature not the grammar or sintaxis):

``` less
@import "bower_components/material-design-color-palette/less/variables.less" "../../bower_components/material-design-color-palette/less/variables.less";
```

so if the first file is not found, it will search for the following, and if not found, it will trigger a `FileError`.

That will fix scenarios like https://github.com/zavoloklom/material-design-typography/issues/3

Thanks

**Comment by seven-phases-max** [comment]
Won't 
```less
@import "../../bower_components/material-design-color-palette/less/variables.less"
@import (optional) "bower_components/material-design-color-palette/less/variables.less"
```
or something like that do the same?
Finally this is what a lazy-evaluation is primarily about (i.e. instead of bothering with *file* overrides we override *variables* (or other *values* in general)).

---
Ah, I actually see you've already considered that variant in https://github.com/zavoloklom/material-design-typography/issues/3.
In general it's probably nothing wrong with the proposed feature too, though it's a bit concerning if the feature is just to meet a potential misuse.

**Comment by diosney** [comment]
what?! no pliz! bumping this.

**Comment by seven-phases-max** [comment]
>bumping this

You did not make any comments on the working code I gave above (it's already working equivalent for the feature). So since a. Less is still tries to stay a minimalistic thing (a feature is not to go in just bacuse "it's possible", especially if the same is possible by other means). b. `@import` directive is larady burdened to the death by verios options. c. (if I'm not mistaken) this can be implemented as a plugin. d. Noone (but two of us) is even commented this FR not even mentioning is going to implement anything like this. The "slate" end seems to be somewhat expected.

**Comment by seven-phases-max** [comment]
Beside (thinking over the use-case from scratch): the problem laying beyond the language itlself should be solved beyond the language. I.e. instead of the particular language statement to try to find some file within a list of possible locations, what you really need is an option to specify this list of the locations to search. 
And the option exists: [`paths`](http://lesscss.org/usage/#command-line-usage-include-paths) (the option is also available programmaticaly as well as in all major task-runners e.g. gulp/grunt).
E.g. set `path` to `bower_components; ../../bower_components` and import as:
```less
@import "material-design-color-palette/less/variables.less";
```

**Comment by matthew-dean** [comment]
@seven-phases-max I agree this is a pathing / file-manager problem.

**Comment by diosney** [comment]
Ok for me then :)
