### ISSUE TITLE
Less breaks when using non breaking spaces (NBSP)

### ISSUE THREAD

**Issue by hampuskensing** [less/less.js#2963]
Less in unable to compile when there are non breaking spaces present, and does not give a sufficiently good error message.

[less2css example](http://less2css.org/#%7B%22less%22%3A%22.test%20%7B%5Cn%20%20color%3A%C2%A0blue%5Cn%7D%22%7D)

`.test { color: blue }`

> ParseError: Unrecognised input. Possibly missing opening '{' on line 3, column 1:
> 2   color: blue
> 3 }

**Comment by rjgotten** [comment]
The CSS Syntax Module, Level 3 defines valid whitespace tokens as:

>A newline, U+0009 CHARACTER TABULATION, or U+0020 SPACE. 
> &mdash; https://www.w3.org/TR/css-syntax-3/#whitespace

Non-breaking spaces shouldn't be treated as whitespace, at least.

Not sure why the parser would not pull the non-breaking space into the preceeding classname in your example though. Maybe a bad regex, because the general whitespace and word boundary matches from regexes *do* count non-breaking spaces as whitespace and word boundary, iirc.
