### ISSUE TITLE
Compiler : how to configure number of digits for hex colors

### ISSUE THREAD

**Issue by franck-grenier** [less/less.js#3025]
Hello,
I'd like to be able to set the number of digits the compiler writes for hex colors.

The default behaviour seems to be different between 2.7.1 and 2.7.2 : 
- 2.7.1 - `#ffffff` => `#ffffff`
- 2.7.2 - `#ffffff` => `#fff`

Is it possible to configure the compiler so that it would keep 6 digits ?

Thanks

**Comment by seven-phases-max** [comment]
No, there's no such option (in general it won't make any sense since both values are equal) - unless you're using `-x` which is deprecated a while ago.
So what is your code exactly and how do you compile it? (Because according to the self tests:
* https://github.com/less/less.js/blob/v2.7.1/test/css/colors.css#L2-L17
* https://github.com/less/less.js/blob/v2.7.2/test/css/colors.css#L2-L17
either long or short values are preserved in these versions).

**Comment by franck-grenier** [comment]
I compile through PHPStorm IDE.

The compilation command is launched without any special options, only the less file to compile.

I agree it's not really a problem. The issue for me is that it pushes changes on files that did not really changed. The other subject is that behaviour seems different for my team mates. The first one changes hex colors to 3 digits and the next one changes everything to 6 digits...

So it would be great to have a configuration parameter so that everybody compiles the same way.

**Comment by seven-phases-max** [comment]
>The other subject is that behaviour seems different for my team mates. 

And since there's no difference in this area between 2.7.1-2.7.2, it's still not clear why exactly the result of your team mates is different (And looking for an option sounds like an attempt to hide the problem rather than to solve it). 

>So it would be great to have a configuration parameter so that everybody compiles the same way.

The more parameters that change the output exist the more problems with syncing different environments you'll actually have.
