### ISSUE TITLE
Additional units

### ISSUE THREAD

**Issue by Crissov** [less/less.js#3048]
[unit-conversions.js](https://github.com/less/less.js/blob/master/lib/less/data/unit-conversions.js) contains most absolute units found in CSS Values and Units level 4. (It's missing `q` and frequency units for instance.) 

The CSS WG acknowledges the (prior) existence of other units in design and typography, but is unwilling to add more units unless there is proven current and future demand. Therefore, I'd like to add some units to preprocessors which, of course, would need to convert them to something CSS UAs understand. Would this be in scope of _less_?

- https://github.com/w3c/csswg-drafts/issues/309
- https://github.com/w3c/csswg-drafts/issues/315
- https://github.com/w3c/csswg-drafts/issues/378
- https://github.com/w3c/csswg-drafts/pull/848

I would be willing to write the [pull request](https://github.com/Crissov/less.js/blob/units/lib/less/data/unit-conversions.js) myself, but I'd be grateful for pointers to files that would need to be changed as well.

**Comment by seven-phases-max** [comment]
>unit-conversions.js contains

It contains only units convertible to each other (e.g. `1s = 1000ms` and so on). This map is used only in certain relational ops (e.g. `5m > 5mm`) and related functions (e.g. `max(5m, 5cm, 5mm)`). Aside of that Less is (and should remain) "unit-unaware" in general - any identifier following a number is considered to be a unit (e.g. `whatever` in `1whatever` is also a unit in Less).

<sub>(To be honest, *personally* I'd vote to remove this conversion stuff from core since it's only polluting the code-based with no practical outcome at all... You're barely find any real project with all those multiples-of-meter units ever used at all, and deg/rad or s/ms being barely ever compared/converted to each other... So the feature was purely "it would be cool to have"-like academic exercise making no sense in a real world of "Where Less is used" context).</sub>

> I'd like to add some units to preprocessors which, of course, would need to convert them to something CSS UAs understand.

A plugin subsystem was developed exactly for this kind of the language extensions.  So basically you start with a visitor plugin where you convert your specific units to standard units and that's it.
For details on visitor plugins see:
* http://lesscss.org/usage/#plugins-for-plugin-authors
* a minimal visitor code in tests: https://github.com/less/less.js/blob/v2.7.2/test/plugins/visitor/index.js (to my taste it's somewhat over-engineered though)
* various visitors in the core itself: https://github.com/less/less.js/tree/v2.7.2/lib/less/visitors
