### ISSUE TITLE
Unexpected DR scope visibility results

### ISSUE THREAD

**Issue by wjtGitHub** [less/less.js#3075]
## Official document
> source
```
@variable: global;
@detached-ruleset: {
  // will use global variable, because it is accessible
  // from detached-ruleset definition
  variable: @variable; 
};

selector {
  @detached-ruleset();
  @variable: value; // variable defined in caller - will be ignored
}
```
> result
```
selector {
  variable: global;
}
```

## actuality
> source
```
@variable: #abc;
@detached-ruleset-test: {
  color: @variable; 
};
.selector {
  @detached-ruleset-test();
  @variable: #def;
}
```
> result
```
.selector {
  color: #def;
}
```

> less version is 2.7.2

**Comment by rjgotten** [comment]
Detached rulesets pull both caller and definition scope into closure, giving precedence to caller scope.
Not a bug; but definitely weird behavior, which will hopefully be removed sometime in the future.

**Comment by seven-phases-max** [comment]
I can't reproduce your "actuality" results in `v2.7.2` so more details needed.

**Comment by rjgotten** [comment]
> No, neither DRs nor mixins (unless defined/invoked with parametric namespace) ever did this

I thought this was actually reported before in another issue and was deemed expected behavior then?

**Comment by seven-phases-max** [comment]
>Perhaps I'm mixing something up.

Most likely, because it's just how it works and has been working [always](http://less2css.org/#%7B%22less%22%3A%22%40variable%3A%20%23abc%3B%5Cn%5Cn%40detached-ruleset-test%3A%20%7B%5Cn%20%20color%3A%20%40variable%3B%20%5Cn%7D%3B%5Cn%5Cn.selector%20%7B%5Cn%20%20%20%20%40detached-ruleset-test()%3B%5Cn%20%20%20%20%40variable%3A%20%23def%3B%5Cn%7D%22%7D). So @wjtGitHub's problem is elsewhere.
