### ISSUE TITLE
node js ejs template

### ISSUE THREAD

**Issue by ivanromakh** [less/less.js#3078]
When I try to use less with ejs template this is happend. I use next command to create project
twitter-bootstrap -t ejs project
And here is error 

TypeError: Cannot read property 'contents' of undefined
    at Object.parse (C:\node\twittrs-bootstrapp\node_modules\less\lib\less\parse
r\parser.js:117:20)
    at Object.express.compiler.compilers.less.compile (C:\node\twittrs-bootstrap
p\app.js:39:12)
    at C:\node\twittrs-bootstrapp\node_modules\connect\lib\middleware\compiler.j
s:99:24
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

I don`t know what to do.

this is code which are generated by that command

...
app.use(express.compiler({ src : __dirname + '/public', enable: ['less']}));
...

// Now less files with @import 'whatever.less' will work(https://github.com/senchalabs/connect/pull/174)
var TWITTER_BOOTSTRAP_PATH = './vendor/twitter/bootstrap/less';
express.compiler.compilers.less.compile = function(str, fn){
  try {
    var less = require('less');var parser = new less.Parser({paths: [TWITTER_BOOTSTRAP_PATH]});
    parser.parse(str, function(err, root){fn(err, root.toCSS());});
  } catch (err) {fn(err);}
}

**Comment by seven-phases-max** [comment]
Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.
---
>this is code which are generated by that command ... https://github.com/senchalabs/connect/pull/174

I don't think you can use five years old scripts with current Less versions (the API changed since then quite a bit - for instance see http://lesscss.org/usage/#programmatic-usage) and this is actually mentioned at the linked issue too.
