### ISSUE TITLE
less 3.0.0 is incompatible with gulp-less

### ISSUE THREAD

**Issue by Devixx** [less/less.js#3164]
Here's the error I get 
I needed to downgrade to 2.7.3 version
```
node_modules/accord/lib/index.js:29
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 3.0.0 is not currently supported
```

**Comment by seven-phases-max** [comment]
This is basically what major version numbers are about (changes in the API/usage may be and usually are incompatible).
If your're about to upgrade you need a corresponding update of the `gulp-less` (thus instead of reporting here you need to create a request at the `gulp-less` issue tracker, e.g. [like this](https://github.com/stevelacy/gulp-less/issues/269)).

**Comment by seven-phases-max** [comment]
Closing as no an issue (and in favour of https://github.com/stevelacy/gulp-less/issues/269).
