### ISSUE TITLE
Simple CSS import in Less file

### ISSUE THREAD

**Issue by Craigy-** [less/less.js#3173]
Hello!

Is there any way to get simple CSS import without processing in less?
I need to get string as is in output file:
`@import "../path-to-css/style.css";`

I have a problem with relative paths and I think it's a most fast and simple way to resolve it.

**Comment by seven-phases-max** [comment]
Hmm, could you eaborate? Because it [already works this way](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%40import%20%5C%22..%2Fpath-to-css%2Fstyle.css%5C%22%3B%22%7D).
Or do you mean something else (like expecting the compiler to translate your relative path to some other path - then see the corresponding [options](http://lesscss.org/usage/#less-options) - it's a lot)?

**Comment by Craigy-** [comment]
Sorry, it's my bad. I'm using gulp to compile less.
Problem in clean-css processing not less.
