### ISSUE TITLE
bundling less 3.0.1 with web-pack, targeting web-worker.

### ISSUE THREAD

**Issue by dasdeck** [less/less.js#3178]
Hi!

I can not get less 3.0.1 to bundle properly into my web worker code.
Less 2 was working flawlessly with the same setup.

When I import less like this:
```
import less from 'less';
```
I get `less.js:78 Uncaught ReferenceError: window is not defined` in the browser console, which kind of makes sense, as the bundle uses the `dist` version for the browser but a worker has no `window`.

since the imports are static, I see no way of shimming the window away.

in the old version we did it like this:

```
import browser from 'less/browser'
const less = browser({},{});
```
which would set a window object.

This bundle, however, throws an error:
```
Cannot find module "."
```

which seems to be related to this particular line of code:
./browser/plugin-loader.js:9
```
var PluginLoader = function(less) {
    this.less = less;
    // shim for browser require?
    this.require = require;    <----------
};
```

here is my web-pack conf.
```
/* eslint-env node */

const conf = {

    entry: {
        'sidebar/test/app': './sidebar/test/app',
        'fields/test/app': './fields/test/app',
        'layout-editor/test/app': './layout-editor/test/app',
        'styler/test/app': './styler/test/app',
    },

    output: {
        filename: './[name].min.js'
    },

    externals: {
        vue: 'Vue',
        uikit: 'UIkit'
    },

    node: {
        fs: 'empty'
    },

    target: 'web',

    module: {

        rules: [
            {
                test: /\.vue$/,
                use: {
                    loader: 'vue-loader',
                    options: {
                        loaders: {
                            js: 'babel-loader?presets[]=env&plugins[]=lodash&plugins[]=transform-object-rest-spread'
                        }
                    }
                }
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env'],
                        plugins: ['lodash', 'transform-object-rest-spread']
                    }
                }
            }
        ]
    }

}

module.exports = (env, argv) => ([conf, 
    {...conf, 
        entry: {'styler/lib/worker': './styler/lib/worker'}, 
        target: 'webworker',
    }]);

```

Cheers!

JM

**Comment by joepvl** [comment]
I'm using Less in a Web Worker as well, and also ran into issues with the new version. I'm not using any plugins or any of the browser functionality (automatically processing stylesheets in the DOM etc.) in my app, so for my case I was able to solve it as follows:

```js
// in my worker
import Less from 'less/lib/less';
const less = Less();
less.PluginLoader = function() {};

less.render(/* your input */).then(result => console.log(result.css))
```

However, I was also running into Webpack build errors because of some inline `require('promise')` calls inside the `less` package. I didn't need or want `promise` as a dependency, so I ended up going with the following hack:

```js
// in my webpack config
import ReplacePlugin from 'webpack-plugin-replace';

const config = {
  // ...
  plugins: [
    // ...
    new ReplacePlugin({
      exclude: /.*/,
      include: /node_modules\/less/,
      values: {
        "require('promise')": 'Promise'
      }
    }),
    // ...
  ]
  // ...
};
```

If you do actually need Less plugins and are directly or indirectly importing e.g. `less/lib/less-browser/plugin-loader` for that reason, you can expect Webpack to choke on the `this.require = require` line as well (or your browser might choke on the result), like what you're describing. Not sure if it's ever used though; you could try applying the same ReplacePlugin hack to that (for example replacing the line with `''` or changing it into `this.require = function() {}`).

Not exactly pretty solutions, I know! 😅

**Comment by dasdeck** [comment]
Thanks for your help!
This did not help me yet, but it gets me some ideas for more things to try, so thanks for the input!
We need to use our plugin though, which might make it more difficult.

Cheers!

**Comment by joepvl** [comment]
My pleasure, but I have since found out, after some more poking and prodding, that I was basically completely wrong! My code/build "worked" for other reasons, and ReplacePlugin does not seem to do any work on the code before it reaches Webpack's processing/resolving logic (I don't know if this is even possible within Webpack), so importing `less/browser` will yield that same "`Cannot find module`" error because of the `this.require = require` line, in which the second `require` is replaced by some code generated by Webpack. In the end, I think this is basically because this code was not written with Webpack in mind. It seems like the browser-based `require` is actually (indirectly) passed to plugins in `AbstractPluginLoader#evalPlugin` (see [abstract-plugin-loader.js#L66](https://github.com/less/less.js/blob/v3.0.0/lib/less/environment/abstract-plugin-loader.js#L66)). This isn't compatible with Webpack's `require` mechanism, so it will complain:
```
WARNING in ./node_modules/less/lib/less-browser/plugin-loader.js
    12:19-26 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
     @ ./node_modules/less/lib/less-browser/plugin-loader.js
     @ ./node_modules/less/lib/less-browser/index.js
     @ ./node_modules/less/browser.js
     @ ./node_modules/babel-loader/lib!./app/lib/LessWorker.js
```
This isn't the type of dynamic `require` call you could fix using ContextReplacementPlugin as far as I can tell, since it is basically "too dynamic".

PS In addition to the above, I wrongly assumed that ReplacePlugin's `include` option would override `exclude`, so my setup actually did nothing because it excluded all paths. Yay, programming!

**Comment by joepvl** [comment]
#### TO ANYONE ELSE READING THIS: this is _NOT_ a recommended way of doing things, _especially_ in production!

You almost may as well fork Less.js to modify it for your own purposes at this point, which may actually be a better solution. I am only posting this for the sake of completeness. Hopefully we can find a way to officially support running Less in a web worker soon.

---

@dasdeck I was hacking around some more just now, and found a way to make it work, albeit in a very dirty way by most standards.

I even added the pi plugin from the docs, which seems to work as well (it loads, and calling `pi()` in the stylesheet will output `3.14159265`), but it's only adding a very simple function so I don't know whether more complex plugins (e.g. visitors) would work.

Basically, it loads the precompiled version from `less/dist/less.js` into a raw string and evaluates that using the `new Function` method, injecting `window` and `document` shims that fulfil the bare minimum into the result. I'm guessing raw-importing the minified version would also work, btw. Here it is:

```js
// using raw-loader here to import the file as a string
import LessRaw from 'raw-loader!less/dist/less';

const PiPlugin = {
  install: function(less, pluginManager, functions) {
    functions.add('pi', function() {
      return less.dimension(Math.PI);
    });
  }
};

const location = {
  href: '',
  protocol: 'https'
};

const document = {
  getElementsByTagName: () => [{ dataset: {} }],
  location
};

const window = {
  document,
  location,
  // less options that get picked up during Less initialization
  less: {
    onReady: false,
    plugins: [
      PiPlugin
    ]
  }
};

// put it all together
const Less = new Function('window', 'document', `${LessRaw}\n return window.less;`);
const less = Less(window, document);

// worker code
self.onmessage = function({ data }) {
  // `data` being Less code that you got from whatever posted the message to your worker
  less.render(data)
    .then(result => self.postMessage(result.css))
    .catch(error => console.warn('Error in worker', error));
};
```

**Comment by rjgotten** [comment]
@joepvl
Use a specialized loader in your webpack config, chained to run before your worker-loader. Have that loader inject `document` and `window` shims as global variables within the worker, before the main Less modules are imported and can run.

To handle the problems surrounding the `require` call:
It is possible to replace the `pluginLoader` with another loader that _is_ webpack compatible via a module alias that can redirect `less/lib/less-browser/plugin-loader` to whatever module of your make is holding your webpack-compatible version.

What you then need to do is replace the unbound variable reference to `require` that is here:
https://github.com/less/less.js/blob/efa6eb5306f28a7ef7e235d79ce854b780345591/lib/less-browser/plugin-loader.js#L9-L13
&mdash; with a reference to an AMD compliant loader that is capable of working inside web workers.

**Comment by rjgotten** [comment]
> I didn't know you could use a loader to inject things to be globally available to imported modules.

You might not even need a dedicated loader to inject globals into the worker source here.
I think you can rely on the fact that imports are resolved in-order and change your worker's module to:

```js
self.window = require( "window-shim" );
self.document = require( "document-shim" );

var less = require( "less" );
```

That will create `window` and `document` as members of the worker's top-level object, which _should_ be enough to have them be used by the less compiler, as otherwise unbound variable references should translate to properties on the top-level object.

**Comment by matthew-dean** [comment]
@dasdeck FYI, this line
```js
this.require = require;
```
...is removed in this PR - https://github.com/less/less.js/pull/3229

**Comment by joepvl** [comment]
@matthew-dean thanks for taking the time to explain, I appreciate it!

**Comment by eight04** [comment]
Here is a browserified bundle that can be used in the browser directly:
https://github.com/openstyles/less-bundle
