### ISSUE TITLE
Option to convert shorthand property declarations to longhand?

### ISSUE THREAD

**Issue by determin1st** [less/less.js#3189]
Hello,

I'm extensively use only cascade blocks power. Like the simplicity of less syntax over others.
So, the question is about plans on development. longhand properties are only "true" because they are returned as computed style in browser. converting to longhand will improve speed over size, i see it in animation task. It could be nice todo-feature to have.

**Comment by seven-phases-max** [comment]
I think it's more ike out of the scope of the language (in general it's not meant to analyse, optimize, understand, guess, transform etc. etc. the CSS output. Less is only about Less to CSS translation and the rest is upto external tools like minifiers, autoprefixers, css-comb etc. and so on).

**Comment by determin1st** [comment]
That would be true if there were no css value interpretations in less (they are), or, there would be an option to turn it off. CSS group, or whoever works on CSS evolution probably will continue their work on value side (like calc() function). They dont see that there is also a key (key: value). Anyway, I re-checked `document.styleSheet` docs, interface is still tiny, the `cssRule.cssText` translates to shorthand if the full set of longhand (padding, for example) is specified. So, maybe it's too early to speak about it.

**Comment by determin1st** [comment]
There is. I wounder why you insist on reverse. If it converts value part, it converts it, it works with it.. etc.
`rgba()` and colors are not as trivial as you think. The conversion of rgba() to hex is not "good" nowadays, because the value may be involved in animations (fading color with alpha part, for example). And this happens by default. It is bad.

Feature may belong to LESS, i belive, so you can "beat up" your competitors. But I don't insist. I like less as it is for now, and use it.

**Comment by seven-phases-max** [comment]
I'm not going to keep argueing with anything. Just because it's not about "convincing someone where it belongs to" but about "finding someone who implements this (regardless of what tool it will be) - i.e. realize it's not going to be implemented even if you convince me it belongs to Less (unless you're about implementing this yourself).
(I'm not sure even sure you're serious to argue with *me* of how Less (learn the name please) works internally).


>The conversion of rgba() to hex is not "good" nowadays, because the value may be involved in animations

Uh, I suggest you to learn more about how colors work in browsers (Hint: `#123451 color value is *absolutely identical* to `rgba(18, 52, 86, 1.0);` with or w/o any animations involved. So wherever you read about the opposite it's misinformation).

**Comment by determin1st** [comment]
Okay okay, I have no knowledge about syntax parser for now.
But I disagree with you about the colors. l will make my mind and return.

**Comment by matthew-dean** [comment]
Closing as out of scope.
