### ISSUE TITLE
@import: try .less extension even when there's a dot (.) in the filename

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3288]
Not sure if this is a bug or a feature request, but it'd be nice if this Less would try to assume `.less` even if there's a `.` in the filename.

### For example:

_css/bootstrap.less_
```less
//...
@import 'bootstrap.theme';
```
I was hoping it'd import _bootstrap.theme.less_, but instead it throws this error:
```
css/bootstrap.less: [L68:C0] 'bootstrap.theme' wasn't found. Tried - css/bootstrap.theme,css/bootstrap.theme,npm://bootstrap.theme,bootstrap.theme
```

---

This is also the case for `@plugin` with `.js` assumption, by the way.  It only checks `.js` if there's no `.` in the filename.

**Comment by calvinjuarez** [comment]
Marking as a bug for now, since I don't remember reading anything that would suggest it's not supposed to be supported.

**Comment by matthew-dean** [comment]
@calvinjuarez This is valid...I suppose. Although it multiplies the number of filename variations that need to be tried. Which on Node is not a big deal I guess.

**Comment by Alexia** [comment]
**Version:** Less.js 3.9.0 running through Node.js.  Included in the hydrawiki/lessoid project.

Running through the logic in less-node/file-manager.js it:

1.) Attempts the full file path as given.
2.) If an exception is caught it calls its local tryWithExtension() shim to require the file with the extension appended.
3.) Inside that shim it calls tryAppendExtension() from abstractFileManager.  However, it does not appear tryAppendExtension() does what tryWithExtension() is intending to do.(Append the extension and try again.)  Since the files to be required already have a `.` in them tryAppendExtension() does nothing.

So it seems like in the case of less-node/file-manager.js there is a mismatch in the responsibilities of what is expected of tryAppendExtension().

```
FileError: 'mediawiki.mixins' wasn't found. Tried - mediawiki.mixins,npm://mediawiki.mixins,mediawiki.mixins,extensions/Echo/modules/nojs/mediawiki.mixins,resources/src/mediawiki.less/mediawiki.ui/mediawiki.mixins,extensions/MobileFrontend/mobile.less/mediawiki.mixins,skins/MinervaNeue/minerva.less/mediawiki.mixins,resources/src/mediawiki.less/mediawiki.mixins in - on line 4, column 1:
3 @import '../echo.variables';
4 @import 'mediawiki.mixins';
5 
```

To work around this issue locally I patched that function since we only use the less-node version.  I do not believe this would be a comprehensive fix for all implementations of Less.js.

```
diff --git a/vendor/hydrawiki/lessoid/services/lessoid/less-hydra/lib/less/environment/abstract-file-manager.js b/vendor/hydrawiki/lessoid/services/lessoid/less-hydra/lib/less/environment/abstract-file-manager.js
index 36428f0614..5940338756 100644
--- a/vendor/hydrawiki/lessoid/services/lessoid/less-hydra/lib/less/environment/abstract-file-manager.js
+++ b/vendor/hydrawiki/lessoid/services/lessoid/less-hydra/lib/less/environment/abstract-file-manager.js
@@ -17,7 +17,7 @@ abstractFileManager.prototype.getPath = function (filename) {
 };
 
 abstractFileManager.prototype.tryAppendExtension = function(path, ext) {
-    return /(\.[a-z]*$)|([\?;].*)$/.test(path) ? path : path + ext;
+    return /(\.[a-z]*$)|([\?;].*)$/.test(path + ext) ? path + ext : path;
 };
 
 abstractFileManager.prototype.tryAppendLessExtension = function(path) {
```
