### ISSUE TITLE
import with tilde for node_modules package

### ISSUE THREAD

**Issue by romuleald** [less/less.js#3342]
I'm looking the simpliest way to import less files with the ~alias from a node_modules like less loader in webpack.

`FileError: '~@folder/composant/file.less' wasn't found`

It seems that less can't understand this. Since I don't need webpack here, is there any solution here?

Just made a test in the: `FileManager.prototype.loadFile` and added a dirty `filename = filename.remplace('~', '');` .
Then added `include-path=node_modules` in my CLI and it worked.

What would be the best way to improve this? I could make the pull-request.

**Comment by matthew-dean** [comment]
Just write `@import "folder/composant/file.less";`

**Comment by KevinRamharak** [comment]
@matthew-dean This currently does not work as (I) expected with a global `less` install. The cause seems to be that NodeJS does not resolve a file based on the current working directory.

Steps to reproduce:
- Create an empty folder
- `npm install bootstrap@3.3.7` (happens to be my use-case)
- Create `test.less` inside the empty folder
- insert `@import "bootstrap/less/bootstrap"`
- compile with `lessc test.less` (Installed as global package)
This will fail with:
```
FileError: 'bootstrap/less/bootstrap.less' wasn't found. Tried - C:\Users\kevin\AppData\Local\Temp\less\bootstrap\less\bootstrap.less,
C:\Users\kevin\AppData\Local\Temp\less\bootstrap\less\bootstrap.less,
npm://bootstrap\less\bootstrap.less,bootstrap\less\bootstrap.less in C:\Users\kevin\AppData\Local\Temp\less\test.less on line 1, column 1:
1 @import "bootstrap/less/bootstrap.less";
```

The line `npm://bootstrap\less\bootstrap.less,bootstrap\less\bootstrap.less` implies that the FileManager uses `[require.resolve](https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L79)` to attempt to resolve it as a node module but it wont look in the current working directory because it is invoked from the global install directory.

after altering the `require.resolve` to `require.resolve(fullFileName, { paths: [ '.' ] });` inside my global install of less the file will be resolved without a problem. The options argument seems to be only support by node `>8.9`. I cannot find another way to solve this problem (at least not one that isn't a hack). Do you have any thoughts on the matter? I could make a pull request once I know the preferred way to solve this.

**Comment by rjgotten** [comment]
> I cannot find another way to solve this problem (at least not one that isn't a hack).

You could use the `resolve` package maintained by browserify.
It aims to reproduce the native NodeJS's module resolution as faithfully as possible.

**Comment by KevinRamharak** [comment]
@rjgotten The problem is that for my use case i have no control over the node environment nor less executable. My team uses a visual studio extension named web compiler. This compiler uses a local install of less and uses the executable `lessc` inside that installation. The shell command executed by the extension looks like the following
```shell
$ # the enviroment state
$ pwd
/my/project/
$ tree
- .
  - less
     - style.less
  - css
     - style.css
  - node_modules/
    - bootstrap
       - less
         - bootstrap.less

$ # the command executed by the extension
$ /visualstudio/extensions/webcompiler/lessc /my/project/less/style.less /my/project/css/style.css
```
an `@import 'bootstrap/less/bootstrap.less'` inside `./less/style.less` will not resolve to `./node_modules/bootstrap/less/bootstrap.less` (or any parent directory with a `node_modules` folder). 
I would expect `lessc` to resolve npm imports regardless of its install path. It is not 

I cannot do a relative import because of npm flattening dependencies I cannot guarantee its path.

**Comment by matthew-dean** [comment]
If it's not resolving the project's node_modules, that's a bug. I think I originally had a `process.cwd()` path added to the Node paths, but was challenged on that by some core devs, and it seemed to work without it.

However, it's unclear to me why `require.resolve` would not resolve according to the project? I guess it's because it's calling require from within `less` code? I don't understand why NPM resolution would be coded that way. Is this an expected behavior of NPM? I would think `require` would behave the same when called from a project even if the require'd module is global.

Wouldn't the obvious solution, though, be to have `less` be local? If you're compiling a project, and `less` is a dependency, it should be in your dependencies. If NPM treats a global require as "exiting" your project and your dependency tree, then it seems like you're butting up against a behavior of NPM, not Less.

I know that Less documents to install the module globally, and that probably should not be the case, because of this side-effect (or if a global install is advocated, then maybe some workaround should be found).

I think more feedback is needed from @less/core about what approach is needed.

**Comment by matthew-dean** [comment]
@KevinRamharak I'd also be curious to know where that extension is executing _from_. That is, is it executing from that project root, or from some other context that effects module resolution. Maybe this isn't an NPM side effect and could also be a poorly written extension? More investigation is probably needed.

**Comment by rjgotten** [comment]
>  My team uses a visual studio extension named web compiler.

Then I would advise you to contact its maintainers and make this their problem to resolve.

Imho this type of scenario based on folder indirections is an edge-case. And I don't think it's something that should be solved by the core lessc developers or something that should be solved in the built-in file or import managers.

Less is extensible enough for affected parties to resolve this type of issue locally, with their own tailored solutions. I'll give you an example as relating to my own situation. Coincidentally, also related to this web compiler extension.

When web compiler was created it also removed the side-by-side preview window for Less compilation that was present in its precursor web essentials. Mads Kristensen, the extension's primary author and maintainer, promised to bring it back. But that promise rang hollow.

So I built my own side-by-side preview extension which has a NodeJS entry point residing in a VS extension housed in the `VisualStudio/Extensions` folder, but uses Sindre Sorhus's [`resolve-from`](https://www.npmjs.com/package/resolve-from) package to attempt to resolve an installation of Less starting from the root of the opened Visual Studio project and perform compilations with that - ensuring the preview window uses the same compiler version as the actual build targets. This `resolve-from` package works fine for that purpose.

The less compiler allows for custom file and import managers to resolve paths. Infact; this is the supported extension point that Webpack's `less-loader` uses to perform its 'magic' as well.

Web compiler's maintainers should be perfectly able to write and register a custom file or import manager for `lessc` that leverages the same `resolve-from` package or a similar package to start module path resolution from the root of the open Visual Studio project instead.

**Comment by KevinRamharak** [comment]
@matthew-dean 
> . If NPM treats a global require as "exiting" your project and your dependency tree, then it seems like you're butting up against a behavior of NPM, not Less.

I realize its not so much the behaviour I expect from less but the behaviour I expect from `require.resolve`. I would agree that this is not a problem that less should try to solve as this is just the behavior of its host nodejs. This does mean however that a global install is limited in its npm imports. Maybe this should be documented?

> Wouldn't the obvious solution, though, be to have less be local? If you're compiling a project, and less is a dependency, it should be in your dependencies

I would love to switch to sane tools and sane dependency management but my team relies heavily on Visual Studio. I use normal tools to maintain a less library where this problem does not occur. This library gets consumed as an npm package inside Visual Studio projects where the problem occurred.

> Maybe this isn't an NPM side effect and could also be a poorly written extension?

The state of the extension could definitely be improved, but this specific case does not only happen inside the extension. The same problem will occur with a global less install as stated in my reproduction steps.

@rjgotten thanks for the extensive reply. Your example should make this a lot easier to solve.

>This type of scenario based on folder indirections is an edge-case. And I don't think it's something that should be solved by the core lessc developers.

Agreed, I will look into contacting the extension maintainers.

> Web compiler's maintainers can write and register their own custom file or import manager that leverages the resolve-from package or a similar package to start module path resolution from the root of the open Visual Studio project. That should work fine.

I think this is a perfectly fine solution for this use case.

> The latter. It's executing from a file inside the centralized VisualStudio/Extensions folder, which diverges from the root of the open Visual Studio project. Took me a bit to figure out how to work around that problem properly myself, but it wasn't that hard.

It took me quite a while to figure it out 😛
Tough I am confused why the extension directory matters as this problem happens in any less install outside of the project.

After some digging in the [source code](https://github.com/madskristensen/WebCompiler/blob/master/src/WebCompiler/Compile/LessCompiler.cs#L84) it seems that currently the working directory is to the directory of the input file. But when invoking the compiler from the task runner explorer [the working directory seems to be the extensions config file directory](https://github.com/madskristensen/WebCompiler/blob/master/src/WebCompilerVsix/TaskRunner/WebCompilerTaskRunner.cs#L51) which is usually the project root. I Have no idea why those are different, but  both methods will fail importing npm packages from the project since the install still resides in the extensions folder.

I think a note in the documentation that states a global less install (or really any folder other than the project folder) might fail to import npm modules because of `require.resolve`'s behaviour.

The rest of the problem seems to be outside the scope of less.

**Comment by rjgotten** [comment]
> both methods will fail importing npm packages from the project since the install still resides in the extensions folder

That's because `require` always looks for a `node_modules` folder starting from the location of the file from which it was called. It doesn't use the current working directory. 😉

**Comment by zhaoyao91** [comment]
Hi, there is a diverse of the styles of import less from node_modules. In webpack apps it requires a tilde before package name, but for lessc, the tilde is invalid, even the webstorm only recorgnize import with tilde. This situation prevent us from writing general less lib which can be shared between other lessc lib or webpack apps.

**Comment by matthew-dean** [comment]
@zhaoyao91 The tilde is because the webpack plugin (which Less does not maintain) converts the path to an NPM-related path, which is not necessary since Less 3. A path without a tilde will resolve to an NPM path.

**Comment by zhaoyao91** [comment]
> @zhaoyao91 The tilde is because the webpack plugin (which Less does not maintain) converts the path to an NPM-related path, which is not necessary since Less 3. A path without a tilde will resolve to an NPM path.

- Does this mean that we can safely use no-tilde import in webpack apps nowadays?
- I found current Webstorm doesn't recognize such import

**Comment by rjgotten** [comment]
> Does this mean that we can safely use no-tilde import in webpack apps nowadays?

If you _only_ need to import from an NPM package, then: yes you can safely avoid the `~`.
(This is not the case when you need Webpack to still apply loaders, but that's a very -- very -- deep edge case anyway.)

> I found current Webstorm doesn't recognize such import

Sounds like a bug or a missing feature in the Webstorm IDE.
