### ISSUE TITLE
Is that possible to customize a import options

### ISSUE THREAD

**Issue by Gcaufy** [less/less.js#3376]
https://www.tutorialspoint.com/less/less_import_options.htm

I'm writing a less plugin, Is that possible to customize a import option in my less plugin?

e.g.

```
@import (myrule) 'abc.less';
```

**Comment by kevinramharak** [comment]
I don't know much about tutorialspoint, but id suggest the [official docs](http://lesscss.org/features/#plugin-atrules-feature)

Looking at the [parser](https://github.com/less/less.js/blob/master/lib/less/parser/parser.js#L1624) source code it seems that the import option is limited to `less|css|multiple|once|inline|reference|optional`.

Maybe you could implement your plugin by using a prefix like the `npm://` example available [here](https://github.com/less/less-plugin-npm-import).

Another option is using a [preloaded plugin](http://lesscss.org/usage/#plugins) to preprocess the source code.

**Comment by matthew-dean** [comment]
Hmm.... technically yes... maybe.... 🤔 

That is, you should be able to write a pre-eval visitor that visits import nodes and does special processing. (You'll probably want to return a proper import node after visiting.)

The only thing I'm sure about is that imports are somewhat of a unique beast, because of the way things are flattened, and they're eval'd early to support variables in import statements. So I'd say... try it?
