### ISSUE TITLE
reduce npm bundle size

### ISSUE THREAD

**Issue by staabm** [less/less.js#3445]
installing less via npm creats a pretty big folder in the node_modules/ directory

![grafik](https://user-images.githubusercontent.com/120441/66757454-867a9480-ee9c-11e9-81d3-66fb3eb33087.png)

it would be great if e.g. the npm published bundle would not include tests or similar.
that way you would save a lot of bandwidth/traffic and also make the life easier for developer which need to work with huge node_modules folders.

more detailed tree:

![grafik](https://user-images.githubusercontent.com/120441/66757613-c9d50300-ee9c-11e9-8085-e5560132f04d.png)

**Comment by matthew-dean** [comment]
@staabm The current plan is a monorepo for 4.0, which separates test data into its own namespaced package. So, in short, this is already in the works, but there's no specific timeline for it.

**Comment by kevinramharak** [comment]
What about using an `.npmignore` file? https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by matthew-dean** [comment]
@kevinramharak The problem is that every time we take source files or tests out of the NPM distribution, we find out that people have built production flows based on those files being present. So it's not that simple when it's a repo with millions of users. The safest time to change this is a major version change.

**Comment by matthew-dean** [comment]
Less test data has been moved to a separate module.
