### ISSUE TITLE
Source Maps Has No Mapping for a Closing Bracket

### ISSUE THREAD

**Issue by BrianMulhall** [less/less.js#3484]
When i generate a source map for the following file using version 3.11.1 

```
.example {
  display: grid;
  transition: all 0.5s;
  user-select: none;
  background: linear-gradient(to bottom, white, black);
}

@color: "blue";

#my-div {
  color: @color;
}
```

with the following command in a node script

```
less.render(lessFileContents, { sourceMap: { sourceMapFileInline: false } })
  .then(function (output) {},
```

Then i look at the Source Map and run it in the https://sokra.github.io/source-map-visualization/#custom tool

```
{"version":3,"sources":["input"],"names":[],"mappings":"AAAA;EACE,aAAA;EACA,oBAAA;EACA,iBAAA;EACA,YAAY,wCAAZ;;AAKF;EACE,OAHM,MAGN"}
```

You can see the empty line in between these two mappings wCAAZ;;AAKF where the mapping for the } should be. This becomes and issue when you are making a source map where this generated map is an intermediate step that you are using to get back to the original Less file.

As an update I have tried Stylus and node-sass and they all do not have a mapping for the closing brackets in the generated file back to the original files. Is this just a limitation of pre processors in general?

**Comment by matthew-dean** [comment]
The simple answer is that Less (currently) has a very simple parser that only tracks source start and not source end, mostly because it was created before source maps were a concept.

I've been re-writing a Less parser from scratch using Chevrotain to use for 4.x, and have done a significant amount of work on it, but without financial support (a la [Open Collective](https://opencollective.com/less)), I can really only work on it in limited free time. I still intend to, but it might take a while.

**Comment by BrianMulhall** [comment]
that makes alot of sense, thanks for the quick response. Ill make a contribution to the open collective on friday. Im excited about the new parser now that I know its coming in the future

**Comment by BarbzYHOOL** [comment]
just wanted to say that Less is awesome
