### ISSUE TITLE
optional brackets, block identation with whitespace

### ISSUE THREAD

**Issue by determin1st** [less/less.js#3534]
maybe a compiler option to move from this:
```
.block
{
  display: flex;
  flex-direction: column;
  &.hidden
  {
    display: none;
  }
}
```
into this:
```
.block
  display: flex;
  flex-direction: column;
  &.hidden
    display: none;
```
like sass does

**Comment by matthew-dean** [comment]
One of Less's features / philosophies is that it's a superset of CSS. That is, a valid Less file, without variables or other Less features, should be a valid CSS file. One of the reasons SCSS exists today is because Less adopted this philosophy when Sass only had indented syntax, so there are no plans to go backwards.
