### ISSUE TITLE
define empty string variable

### ISSUE THREAD

**Issue by vol4ok** [less/less.js#532]
I want to define a variable, which could be empty in some cases
`@prefix: "";`
and to use it like this
`src: url("@{prefix}/path/to/something");`
the problem is that it compiles into
`src: url("""/path/to/something");`

**Comment by huguangju** [comment]
me too

**Comment by seven-phases-max** [comment]
@huguangju The issue is typically closed when it's fixed one way or another. 
So regardless of what was broken in 2012, today the answer to "How to define an empty string" is "As usual":
```less
@empty-string: "";
```
[Demo](http://less2css.org/#%7B%22less%22%3A%22%5Cn%40empty-string%3A%20%5C%22%5C%22%3B%5Cn%5Cnusage%20%7B%5Cn%20%20%20%20src%3A%20url(%5C%22%40%7Bempty-string%7D%2Fpath%2Fto%2Fsomething%5C%22)%3B%20%20%5Cn%20%20%20%20src%3A%20url(~%5C%22%40%7Bempty-string%7D%2Fpath%2Fto%2Fsomething%5C%22)%3B%20%20%5Cn%20%20%20%2F%2F%20etc.%5Cn%7D%5Cn%5Cn%2F%2F%20note%20that%20empty%20string%20is%20different%20form%20just%20an%20empty%20value%3A%5Cn%40empty%3A%20%3B%5Cn%22%7D).

**Comment by huguangju** [comment]
@seven-phases-max thank you.
